import type { AppUser, EaseEventsData } from "./types";

export const demoPasswords = {
  admin: "demo123",
  planner: "demo123",
  client: "demo123",
  vendor: "demo123",
} as const;

export const demoUsers: AppUser[] = [
  {
    id: "user-admin-ava",
    organizationId: "org-coco-cabana",
    role: "admin",
    fullName: "Ava Montero",
    email: "owner@cococabana.demo",
    phone: "416-555-0101",
  },
  {
    id: "user-planner-maya",
    organizationId: "org-coco-cabana",
    role: "planner",
    fullName: "Maya Singh",
    email: "planner@cococabana.demo",
    phone: "416-555-0102",
  },
  {
    id: "user-planner-talia",
    organizationId: "org-coco-cabana",
    role: "planner",
    fullName: "Talia Brooks",
    email: "talia@cococabana.demo",
    phone: "416-555-0103",
  },
  {
    id: "user-client-nisha",
    organizationId: "org-coco-cabana",
    role: "client",
    fullName: "Nisha Patel",
    email: "client@cococabana.demo",
    phone: "416-555-0138",
  },
  {
    id: "user-client-sofia",
    organizationId: "org-coco-cabana",
    role: "client",
    fullName: "Sofia Rivera",
    email: "sofia@cococabana.demo",
    phone: "416-555-0197",
  },
  {
    id: "user-vendor-elena",
    organizationId: "org-coco-cabana",
    role: "vendor",
    fullName: "Elena Brooks",
    email: "vendor@cococabana.demo",
    phone: "416-555-0160",
  },
];

export const initialEaseEventsData: EaseEventsData = {
  organization: {
    id: "org-coco-cabana",
    name: "Coco Cabana Events",
    slug: "coco-cabana",
    timezone: "America/Toronto",
    currency: "CAD",
    emailSenderName: "Ugo @ EaseOps",
    emailSignature:
      "Best,\nUgo @ EaseOps\nFounder & Chief Consultant\n[EaseOps](https://easeops.ca/)",
  },
  users: demoUsers,
  clients: [
    {
      id: "client-nisha-patel",
      organizationId: "org-coco-cabana",
      userId: "user-client-nisha",
      displayName: "Nisha Patel",
      email: "nisha.patel@example.com",
      phone: "416-555-0138",
      status: "Active",
      source: "HoneyBook import",
      notes: "High-touch wedding client with multiple approval handoffs.",
      lifetimeValue: 42000,
      lastContactedAt: "2026-06-17T14:00:00Z",
      createdAt: "2026-05-11T10:00:00Z",
    },
    {
      id: "client-sofia-rivera",
      organizationId: "org-coco-cabana",
      userId: "user-client-sofia",
      displayName: "Sofia Rivera",
      email: "sofia@example.com",
      phone: "416-555-0197",
      status: "Active",
      source: "Referral",
      notes: "Garden bridal shower client. Prefers concise visual updates.",
      lifetimeValue: 16800,
      lastContactedAt: "2026-06-14T18:30:00Z",
      createdAt: "2026-05-20T14:15:00Z",
    },
    {
      id: "client-lena-chen",
      organizationId: "org-coco-cabana",
      displayName: "Lena Chen",
      email: "lena.chen@example.com",
      phone: "647-555-0170",
      companyName: "Chen Foundation",
      status: "Active",
      source: "Website",
      notes: "Foundation gala client with sponsor visibility requirements.",
      lifetimeValue: 73500,
      lastContactedAt: "2026-06-12T15:45:00Z",
      createdAt: "2026-05-27T08:40:00Z",
    },
    {
      id: "client-priya-morrison",
      organizationId: "org-coco-cabana",
      displayName: "Priya Morrison",
      email: "priya.morrison@example.com",
      phone: "905-555-0144",
      status: "Past",
      source: "Instagram",
      notes: "Completed baby shower. Strong referral opportunity.",
      lifetimeValue: 9250,
      lastContactedAt: "2026-06-02T19:10:00Z",
      relationshipStatus: "Retention Follow-Up",
      relationshipOwnerId: "user-planner-maya",
      preferredContactChannel: "Email",
      futureEventCommunicationPreference: "Manual Review",
      relationshipScore: 5,
      firstInquiryAt: "2026-04-28T15:05:00Z",
      lastEventAt: "2026-05-30",
      nextRelationshipAction: "Review referral and family milestone follow-up before outreach.",
      nextRelationshipActionAt: "2027-03-31T14:00:00Z",
      relationshipNotes:
        "Loved the garden palette and mentioned two friends may need event support.",
      createdAt: "2026-04-28T15:05:00Z",
    },
    {
      id: "client-grace-wilson",
      organizationId: "org-coco-cabana",
      displayName: "Grace Wilson",
      email: "grace.wilson@example.com",
      phone: "416-555-0184",
      status: "Prospect",
      source: "Instagram",
      notes: "Interested in tropical dinner party concept.",
      lifetimeValue: 0,
      createdAt: "2026-06-01T13:10:00Z",
    },
  ],
  projects: [
    {
      id: "project-grace-wilson",
      organizationId: "org-coco-cabana",
      leadId: "lead-grace-wilson",
      clientId: "client-grace-wilson",
      ownerId: "user-planner-maya",
      name: "Grace Wilson Luxury birthday dinner",
      stage: "Inquiry",
      lastActivityAt: "2026-06-01T13:14:00Z",
      createdAt: "2026-06-01T13:10:00Z",
      updatedAt: "2026-06-01T13:14:00Z",
    },
    {
      id: "project-jordan-miles",
      organizationId: "org-coco-cabana",
      leadId: "lead-jordan-miles",
      ownerId: "user-admin-ava",
      name: "Jordan Miles Engagement party",
      stage: "Consultation",
      lastActivityAt: "2026-06-02T15:30:00Z",
      createdAt: "2026-05-29T09:35:00Z",
      updatedAt: "2026-06-02T15:30:00Z",
    },
    {
      id: "project-amara-cole",
      organizationId: "org-coco-cabana",
      leadId: "lead-amara-cole",
      ownerId: "user-planner-maya",
      name: "Amara Cole Brand launch",
      stage: "Proposal",
      lastActivityAt: "2026-06-04T11:20:00Z",
      createdAt: "2026-05-24T16:20:00Z",
      updatedAt: "2026-06-04T11:20:00Z",
    },
    {
      id: "project-patel-sangeet",
      organizationId: "org-coco-cabana",
      leadId: "lead-nisha-patel",
      eventId: "event-patel-sangeet",
      clientId: "client-nisha-patel",
      ownerId: "user-admin-ava",
      name: "Patel Sangeet & Reception",
      stage: "Planning",
      lastActivityAt: "2026-06-15T16:20:00Z",
      createdAt: "2026-05-11T10:00:00Z",
      updatedAt: "2026-06-15T16:20:00Z",
    },
    {
      id: "project-evan-martin",
      organizationId: "org-coco-cabana",
      leadId: "lead-evan-martin",
      ownerId: "user-planner-maya",
      name: "Evan Martin Corporate holiday party",
      stage: "Lost",
      lastActivityAt: "2026-05-18T11:45:00Z",
      createdAt: "2026-05-18T11:45:00Z",
      updatedAt: "2026-05-18T11:45:00Z",
    },
    {
      id: "project-rivera-shower",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      clientId: "client-sofia-rivera",
      ownerId: "user-planner-maya",
      name: "Rivera Garden Bridal Shower",
      stage: "Planning",
      lastActivityAt: "2026-06-16T09:15:00Z",
      createdAt: "2026-05-20T14:15:00Z",
      updatedAt: "2026-06-16T09:15:00Z",
    },
    {
      id: "project-chen-gala",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      clientId: "client-lena-chen",
      ownerId: "user-admin-ava",
      name: "Chen Foundation Summer Gala",
      stage: "Finalization",
      lastActivityAt: "2026-06-12T15:45:00Z",
      createdAt: "2026-05-27T08:40:00Z",
      updatedAt: "2026-06-12T15:45:00Z",
    },
    {
      id: "project-morrison-baby",
      organizationId: "org-coco-cabana",
      eventId: "event-morrison-baby",
      clientId: "client-priya-morrison",
      ownerId: "user-planner-maya",
      name: "Morrison Baby Shower",
      stage: "Completed",
      lastActivityAt: "2026-06-02T19:10:00Z",
      createdAt: "2026-04-28T15:05:00Z",
      updatedAt: "2026-06-02T19:10:00Z",
    },
  ],
  connectedAccounts: [],
  calendarSyncStates: [],
  externalCalendarEvents: [
    {
      id: "external-calendar-style-review",
      organizationId: "org-coco-cabana",
      connectedAccountId: undefined,
      provider: "google",
      calendarId: "primary",
      externalEventId: "demo-style-review",
      iCalUid: "demo-style-review@easeevents",
      title: "Vendor styling hold",
      description: "External calendar hold imported from Google Calendar.",
      startAt: "2026-06-22T18:00:00Z",
      endAt: "2026-06-22T19:00:00Z",
      allDay: false,
      timezone: "America/Toronto",
      status: "Confirmed",
      location: "Coco Cabana studio",
      meetingUrl: undefined,
      attendees: ["maya@cococabana.demo"],
      recurrence: {},
      providerUpdatedAt: "2026-06-18T12:00:00Z",
      rawProviderPayload: {},
      syncStatus: "Synced",
      conflictStatus: "Unchecked",
      metadata: {},
      createdAt: "2026-06-18T12:00:00Z",
      updatedAt: "2026-06-18T12:00:00Z",
    },
  ],
  schedulingPreferences: [
    {
      id: "schedule-pref-org-coco",
      organizationId: "org-coco-cabana",
      timezone: "America/Toronto",
      workingDays: [1, 2, 3, 4, 5],
      workdayStart: "09:00",
      workdayEnd: "17:00",
      defaultMeetingDurationMinutes: 30,
      minimumNoticeMinutes: 120,
      bufferBeforeMinutes: 0,
      bufferAfterMinutes: 15,
      metadata: {},
      createdAt: "2026-06-01T12:00:00Z",
      updatedAt: "2026-06-01T12:00:00Z",
    },
  ],
  availabilityBlocks: [],
  calendarConflicts: [],
  calendarSyncRuns: [],
  leads: [
    {
      id: "lead-grace-wilson",
      organizationId: "org-coco-cabana",
      projectId: "project-grace-wilson",
      clientId: "client-grace-wilson",
      ownerId: "user-planner-maya",
      stage: "New Inquiry",
      clientName: "Grace Wilson",
      email: "grace.wilson@example.com",
      phone: "416-555-0184",
      eventType: "Luxury birthday dinner",
      eventDate: "2026-08-22",
      estimatedGuestCount: 70,
      budgetRange: "$12k-$18k",
      notes:
        "Interested in a tropical dinner party with lounge rentals, florals, and a champagne wall.",
      source: "Instagram",
      createdAt: "2026-06-01T13:10:00Z",
    },
    {
      id: "lead-jordan-miles",
      organizationId: "org-coco-cabana",
      projectId: "project-jordan-miles",
      ownerId: "user-admin-ava",
      stage: "Consultation Scheduled",
      clientName: "Jordan Miles",
      email: "jordan.miles@example.com",
      phone: "647-555-0122",
      eventType: "Engagement party",
      eventDate: "2026-09-05",
      estimatedGuestCount: 120,
      budgetRange: "$25k-$35k",
      notes:
        "Venue is shortlisted. Needs decor concept, vendor coordination, and budget guardrails.",
      source: "Referral",
      createdAt: "2026-05-29T09:35:00Z",
    },
    {
      id: "lead-amara-cole",
      organizationId: "org-coco-cabana",
      projectId: "project-amara-cole",
      ownerId: "user-planner-maya",
      stage: "Proposal Sent",
      clientName: "Amara Cole",
      email: "amara.cole@example.com",
      phone: "289-555-0131",
      eventType: "Brand launch",
      eventDate: "2026-10-02",
      estimatedGuestCount: 180,
      budgetRange: "$45k-$60k",
      notes:
        "Needs proposal broken into must-have and stretch options. Client asked for a media wall.",
      source: "Website",
      createdAt: "2026-05-24T16:20:00Z",
    },
    {
      id: "lead-nisha-patel",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      clientId: "client-nisha-patel",
      ownerId: "user-admin-ava",
      stage: "Booked",
      clientName: "Nisha Patel",
      email: "nisha.patel@example.com",
      phone: "416-555-0138",
      eventType: "Sangeet and reception",
      eventDate: "2026-06-28",
      estimatedGuestCount: 260,
      budgetRange: "$40k-$55k",
      notes:
        "Converted from HoneyBook. Requires multiple vendor handoffs and a client approval lane.",
      source: "HoneyBook import",
      convertedEventId: "event-patel-sangeet",
      createdAt: "2026-05-11T10:00:00Z",
    },
    {
      id: "lead-evan-martin",
      organizationId: "org-coco-cabana",
      projectId: "project-evan-martin",
      ownerId: "user-planner-maya",
      stage: "Lost",
      clientName: "Evan Martin",
      email: "evan.martin@example.com",
      phone: "905-555-0110",
      eventType: "Corporate holiday party",
      eventDate: "2026-12-12",
      estimatedGuestCount: 220,
      budgetRange: "$20k-$28k",
      notes: "Paused planning until Q4 budgets are approved.",
      source: "Google Search",
      createdAt: "2026-05-18T11:45:00Z",
    },
  ],
  events: [
    {
      id: "event-patel-sangeet",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      clientId: "client-nisha-patel",
      clientUserId: "user-client-nisha",
      plannerId: "user-admin-ava",
      clientName: "Nisha Patel",
      clientEmail: "nisha.patel@example.com",
      clientPhone: "416-555-0138",
      eventName: "Patel Sangeet & Reception",
      eventType: "Wedding celebration",
      eventDate: "2026-06-28",
      startTime: "17:00",
      endTime: "01:00",
      location: "Arlington Estate, Vaughan",
      guestCount: 260,
      status: "Awaiting Client Approval",
      clientPrice: 42000,
      internalNotes:
        "Client wants a warm, modern palette with high-impact florals. Confirm rain plan with venue.",
      timelineNotes:
        "Vendor load-in begins at 8:00 AM. Client reveal targeted for 4:15 PM before guest arrival.",
      createdAt: "2026-05-12T12:00:00Z",
    },
    {
      id: "event-rivera-shower",
      organizationId: "org-coco-cabana",
      projectId: "project-rivera-shower",
      clientId: "client-sofia-rivera",
      clientUserId: "user-client-sofia",
      plannerId: "user-planner-maya",
      clientName: "Sofia Rivera",
      clientEmail: "sofia@example.com",
      clientPhone: "416-555-0197",
      eventName: "Rivera Garden Bridal Shower",
      eventType: "Bridal shower",
      eventDate: "2026-07-12",
      startTime: "12:30",
      endTime: "16:30",
      location: "Graydon Hall Manor, Toronto",
      guestCount: 84,
      status: "Planning",
      clientPrice: 16800,
      internalNotes:
        "Client approved the garden party palette. Keep rentals compact for venue access.",
      timelineNotes: "Install florals by 10:30 AM. Dessert table photos before guests enter.",
      createdAt: "2026-05-20T14:15:00Z",
    },
    {
      id: "event-chen-gala",
      organizationId: "org-coco-cabana",
      projectId: "project-chen-gala",
      clientId: "client-lena-chen",
      plannerId: "user-admin-ava",
      clientName: "Lena Chen",
      clientEmail: "lena.chen@example.com",
      clientPhone: "647-555-0170",
      eventName: "Chen Foundation Summer Gala",
      eventType: "Fundraising gala",
      eventDate: "2026-08-09",
      startTime: "18:00",
      endTime: "23:30",
      location: "Evergreen Brick Works, Toronto",
      guestCount: 310,
      status: "Confirmed",
      clientPrice: 73500,
      internalNotes: "High sponsor visibility. Production run-of-show needs one owner.",
      timelineNotes: "Silent auction opens at 6:15 PM. Main program starts at 8:00 PM.",
      createdAt: "2026-05-27T08:40:00Z",
    },
    {
      id: "event-morrison-baby",
      organizationId: "org-coco-cabana",
      projectId: "project-morrison-baby",
      clientId: "client-priya-morrison",
      plannerId: "user-planner-maya",
      clientName: "Priya Morrison",
      clientEmail: "priya.morrison@example.com",
      clientPhone: "905-555-0144",
      eventName: "Morrison Baby Shower",
      eventType: "Baby shower",
      eventDate: "2026-05-30",
      startTime: "13:00",
      endTime: "17:00",
      location: "Private residence, Oakville",
      guestCount: 52,
      status: "Completed",
      clientPrice: 9250,
      internalNotes: "Post-event summary should capture the referral opportunity from two guests.",
      timelineNotes: "Completed with no outstanding vendor issues.",
      createdAt: "2026-04-28T15:05:00Z",
    },
  ],
  eventTeamMembers: [
    {
      id: "team-patel-lead",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      userId: "user-admin-ava",
      roleLabel: "Lead planner",
      createdAt: "2026-05-12T12:05:00Z",
    },
    {
      id: "team-patel-producer",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      userId: "user-planner-maya",
      roleLabel: "Production planner",
      createdAt: "2026-05-12T12:10:00Z",
    },
    {
      id: "team-patel-vendors",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      userId: "user-planner-talia",
      roleLabel: "Vendor coordinator",
      createdAt: "2026-05-12T12:15:00Z",
    },
    {
      id: "team-rivera-lead",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      userId: "user-planner-maya",
      roleLabel: "Lead planner",
      createdAt: "2026-05-20T14:20:00Z",
    },
    {
      id: "team-rivera-design",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      userId: "user-planner-talia",
      roleLabel: "Design support",
      createdAt: "2026-05-20T14:25:00Z",
    },
    {
      id: "team-chen-lead",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      userId: "user-admin-ava",
      roleLabel: "Lead planner",
      createdAt: "2026-05-27T08:45:00Z",
    },
    {
      id: "team-chen-logistics",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      userId: "user-planner-talia",
      roleLabel: "Logistics planner",
      createdAt: "2026-05-27T08:50:00Z",
    },
    {
      id: "team-morrison-lead",
      organizationId: "org-coco-cabana",
      eventId: "event-morrison-baby",
      userId: "user-planner-maya",
      roleLabel: "Lead planner",
      createdAt: "2026-04-28T15:10:00Z",
    },
  ],
  vendors: [
    {
      id: "vendor-bloom-haven",
      organizationId: "org-coco-cabana",
      name: "Bloom Haven Floral",
      serviceCategory: "Florals",
      contactName: "Elena Brooks",
      email: "hello@bloomhaven.example",
      phone: "416-555-0160",
      website: "https://bloomhaven.example",
      notes: "Strong with large-scale floral moments and modern ceremony arches.",
      rating: 5,
    },
    {
      id: "vendor-luxe-linen",
      organizationId: "org-coco-cabana",
      name: "Luxe Linen & Rentals",
      serviceCategory: "Rentals",
      contactName: "Marco Di Luca",
      email: "orders@luxelinen.example",
      phone: "416-555-0152",
      website: "https://luxelinen.example",
      notes: "Reliable delivery windows. Ask for inventory holds two weeks out.",
      rating: 4,
    },
    {
      id: "vendor-saffron-table",
      organizationId: "org-coco-cabana",
      name: "Saffron Table Catering",
      serviceCategory: "Catering",
      contactName: "Rina Shah",
      email: "events@saffrontable.example",
      phone: "905-555-0164",
      notes: "Best fit for South Asian fusion menus and late-night stations.",
      rating: 5,
    },
    {
      id: "vendor-brightbox",
      organizationId: "org-coco-cabana",
      name: "BrightBox Photo",
      serviceCategory: "Photography",
      contactName: "Theo Grant",
      email: "studio@brightbox.example",
      phone: "647-555-0165",
      notes: "Fast turnaround for branded and social preview galleries.",
      rating: 4,
    },
    {
      id: "vendor-sonic-arc",
      organizationId: "org-coco-cabana",
      name: "Sonic Arc Entertainment",
      serviceCategory: "Entertainment",
      contactName: "Naomi Lee",
      email: "bookings@sonicarc.example",
      phone: "416-555-0140",
      notes: "DJ plus percussion add-on available for reception entrances.",
      rating: 5,
    },
    {
      id: "vendor-evergreen-venue",
      organizationId: "org-coco-cabana",
      name: "Evergreen Venue Group",
      serviceCategory: "Venue",
      contactName: "Claire An",
      email: "events@evergreenvenue.example",
      phone: "416-555-0129",
      notes: "Preferred event manager is Claire. Strict dock schedule.",
      rating: 4,
    },
    {
      id: "vendor-event-staffing-co",
      organizationId: "org-coco-cabana",
      name: "Event Staffing Co.",
      serviceCategory: "Staffing",
      contactName: "Dev Patel",
      email: "crew@eventstaffing.example",
      phone: "289-555-0107",
      notes: "Great captain pool for high-touch guest experiences.",
      rating: 4,
    },
    {
      id: "vendor-cabana-customs",
      organizationId: "org-coco-cabana",
      name: "Cabana Customs Fabrication",
      serviceCategory: "Decor",
      contactName: "Mila Torres",
      email: "builds@cabanacustoms.example",
      phone: "647-555-0199",
      notes: "Builds statement bars, plinths, signage, and photo moments.",
      rating: 5,
    },
  ],
  eventVendors: [
    {
      id: "event-vendor-patel-florals",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      vendorId: "vendor-bloom-haven",
      serviceCategory: "Florals",
      quotedAmount: 7800,
      actualAmount: 8200,
      paymentStatus: "Deposit Paid",
      notes: "Add mandap floral refresh between ceremony and reception.",
    },
    {
      id: "event-vendor-patel-catering",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      vendorId: "vendor-saffron-table",
      serviceCategory: "Catering",
      quotedAmount: 14200,
      actualAmount: 14500,
      paymentStatus: "Partially Paid",
      notes: "Confirm late-night dosa station headcount.",
    },
    {
      id: "event-vendor-rivera-rentals",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      vendorId: "vendor-luxe-linen",
      serviceCategory: "Rentals",
      quotedAmount: 3800,
      actualAmount: 3800,
      paymentStatus: "Deposit Paid",
      notes: "Hold garden chairs and blush linens.",
    },
    {
      id: "event-vendor-chen-venue",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      vendorId: "vendor-evergreen-venue",
      serviceCategory: "Venue",
      quotedAmount: 18500,
      actualAmount: 18500,
      paymentStatus: "Partially Paid",
      notes: "Venue balance due after final guest count.",
    },
  ],
  budgetItems: [
    {
      id: "budget-patel-decor",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      category: "Decor",
      description: "Custom stage, bar wrap, signage, and lounge styling",
      plannedAmount: 9500,
      actualAmount: 10200,
      vendorId: "vendor-cabana-customs",
      paidAmount: 5000,
      dueDate: "2026-06-20",
      marginEstimate: 4200,
    },
    {
      id: "budget-patel-florals",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      category: "Florals",
      description: "Mandap florals, centerpieces, and entry installation",
      plannedAmount: 7800,
      actualAmount: 8200,
      vendorId: "vendor-bloom-haven",
      paidAmount: 3500,
      dueDate: "2026-06-18",
      marginEstimate: 2100,
    },
    {
      id: "budget-patel-catering",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      category: "Catering",
      description: "Dinner, late-night station, and staff meals",
      plannedAmount: 14200,
      actualAmount: 14500,
      vendorId: "vendor-saffron-table",
      paidAmount: 9000,
      dueDate: "2026-06-24",
      marginEstimate: 3200,
    },
    {
      id: "budget-patel-staffing",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      category: "Staffing",
      description: "Lead planner, assistants, and strike crew",
      plannedAmount: 4200,
      actualAmount: 3900,
      vendorId: "vendor-event-staffing-co",
      paidAmount: 1200,
      dueDate: "2026-06-28",
      marginEstimate: 2500,
    },
    {
      id: "budget-rivera-rentals",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      category: "Rentals",
      description: "Garden chairs, linens, parasols, and glassware",
      plannedAmount: 3800,
      actualAmount: 3800,
      vendorId: "vendor-luxe-linen",
      paidAmount: 1900,
      dueDate: "2026-07-01",
      marginEstimate: 1200,
    },
    {
      id: "budget-rivera-florals",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      category: "Florals",
      description: "Tablescape blooms and dessert display florals",
      plannedAmount: 3200,
      actualAmount: 3100,
      vendorId: "vendor-bloom-haven",
      paidAmount: 1500,
      dueDate: "2026-07-05",
      marginEstimate: 1400,
    },
    {
      id: "budget-rivera-decor",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      category: "Decor",
      description: "Welcome sign, seating chart, and tablescape styling",
      plannedAmount: 4500,
      actualAmount: 4100,
      vendorId: "vendor-cabana-customs",
      paidAmount: 2000,
      dueDate: "2026-07-08",
      marginEstimate: 2500,
    },
    {
      id: "budget-rivera-photo",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      category: "Photography",
      description: "Two-hour lifestyle photo coverage",
      plannedAmount: 1800,
      actualAmount: 1800,
      vendorId: "vendor-brightbox",
      paidAmount: 0,
      dueDate: "2026-07-12",
      marginEstimate: 400,
    },
    {
      id: "budget-chen-venue",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      category: "Venue",
      description: "Venue rental, dock access, and security",
      plannedAmount: 18500,
      actualAmount: 18500,
      vendorId: "vendor-evergreen-venue",
      paidAmount: 9000,
      dueDate: "2026-07-20",
      marginEstimate: 3500,
    },
    {
      id: "budget-chen-entertainment",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      category: "Entertainment",
      description: "DJ, live strings, and awards walk-up music",
      plannedAmount: 6800,
      actualAmount: 7200,
      vendorId: "vendor-sonic-arc",
      paidAmount: 2500,
      dueDate: "2026-08-01",
      marginEstimate: 1600,
    },
    {
      id: "budget-chen-catering",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      category: "Catering",
      description: "Reception canapes, plated dinner, bar package",
      plannedAmount: 26500,
      actualAmount: 27100,
      vendorId: "vendor-saffron-table",
      paidAmount: 12000,
      dueDate: "2026-08-03",
      marginEstimate: 5200,
    },
    {
      id: "budget-chen-staffing",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      category: "Staffing",
      description: "Registration, auction support, and guest services",
      plannedAmount: 7200,
      actualAmount: 6900,
      vendorId: "vendor-event-staffing-co",
      paidAmount: 2000,
      dueDate: "2026-08-09",
      marginEstimate: 2700,
    },
    {
      id: "budget-morrison-decor",
      organizationId: "org-coco-cabana",
      eventId: "event-morrison-baby",
      category: "Decor",
      description: "Balloon wall, dessert backdrop, and tabletop styling",
      plannedAmount: 3100,
      actualAmount: 3000,
      vendorId: "vendor-cabana-customs",
      paidAmount: 3000,
      dueDate: "2026-05-25",
      marginEstimate: 1700,
    },
    {
      id: "budget-morrison-florals",
      organizationId: "org-coco-cabana",
      eventId: "event-morrison-baby",
      category: "Florals",
      description: "Bud vases and welcome table florals",
      plannedAmount: 950,
      actualAmount: 900,
      vendorId: "vendor-bloom-haven",
      paidAmount: 900,
      dueDate: "2026-05-29",
      marginEstimate: 450,
    },
    {
      id: "budget-morrison-rentals",
      organizationId: "org-coco-cabana",
      eventId: "event-morrison-baby",
      category: "Rentals",
      description: "Dessert stands, linens, and lounge vignette",
      plannedAmount: 1650,
      actualAmount: 1600,
      vendorId: "vendor-luxe-linen",
      paidAmount: 1600,
      dueDate: "2026-05-28",
      marginEstimate: 600,
    },
    {
      id: "budget-morrison-staffing",
      organizationId: "org-coco-cabana",
      eventId: "event-morrison-baby",
      category: "Staffing",
      description: "Setup, styling, and strike team",
      plannedAmount: 1300,
      actualAmount: 1250,
      vendorId: "vendor-event-staffing-co",
      paidAmount: 1250,
      dueDate: "2026-05-30",
      marginEstimate: 700,
    },
  ],
  invoices: [
    {
      id: "invoice-patel-deposit",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      clientId: "client-nisha-patel",
      invoiceNumber: "INV-20260601-PATEL",
      invoiceType: "Deposit",
      amount: 21000,
      paidAmount: 12000,
      balanceDue: 9000,
      dueDate: "2026-06-20",
      status: "Partially Paid",
      notes: "Deposit and first production milestone.",
      metadata: { source: "demo" },
      createdAt: "2026-06-01T14:00:00Z",
      updatedAt: "2026-06-12T16:00:00Z",
    },
    {
      id: "invoice-rivera-final",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      clientId: "client-sofia-rivera",
      invoiceNumber: "INV-20260615-RIVERA",
      invoiceType: "Final",
      amount: 8400,
      paidAmount: 0,
      balanceDue: 8400,
      dueDate: "2026-07-05",
      status: "Sent",
      notes: "Final client balance before production week.",
      metadata: { source: "demo" },
      createdAt: "2026-06-15T15:30:00Z",
      updatedAt: "2026-06-15T15:30:00Z",
    },
    {
      id: "invoice-chen-deposit",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      clientId: "client-lena-chen",
      invoiceNumber: "INV-20260610-CHEN",
      invoiceType: "Deposit",
      amount: 36750,
      paidAmount: 36750,
      balanceDue: 0,
      dueDate: "2026-06-18",
      status: "Paid",
      stripeInvoiceId: "in_demo_chen_deposit",
      notes: "Paid deposit invoice.",
      metadata: { source: "demo" },
      createdAt: "2026-06-10T12:00:00Z",
      updatedAt: "2026-06-18T12:00:00Z",
    },
  ],
  tasks: [
    {
      id: "task-patel-budget",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      eventId: "event-patel-sangeet",
      ownerId: "user-admin-ava",
      title: "Send final budget approval packet",
      description: "Bundle budget summary, variance notes, and vendor balance schedule.",
      dueDate: "2026-06-10",
      status: "In Progress",
      priority: "Urgent",
      checklist: [
        {
          id: "check-patel-budget-1",
          organizationId: "org-coco-cabana",
          taskId: "task-patel-budget",
          title: "Review updated catering quote",
          isComplete: true,
        },
        {
          id: "check-patel-budget-2",
          organizationId: "org-coco-cabana",
          taskId: "task-patel-budget",
          title: "Attach approval PDF",
          isComplete: false,
        },
      ],
    },
    {
      id: "task-patel-vendor-call",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      eventId: "event-patel-sangeet",
      ownerId: "user-planner-maya",
      title: "Host vendor production call",
      description: "Walk through load-in, reveal timing, and strike path.",
      dueDate: "2026-06-14",
      status: "To Do",
      priority: "High",
      checklist: [],
    },
    {
      id: "task-patel-floorplan",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      eventId: "event-patel-sangeet",
      ownerId: "user-admin-ava",
      title: "Lock reception floorplan",
      description: "Confirm guest table counts, dance floor size, and stage dimensions.",
      dueDate: "2026-06-17",
      status: "Blocked",
      priority: "High",
      checklist: [],
    },
    {
      id: "task-rivera-moodboard",
      organizationId: "org-coco-cabana",
      projectId: "project-rivera-shower",
      eventId: "event-rivera-shower",
      ownerId: "user-planner-maya",
      title: "Upload revised moodboard",
      description: "Swap linen image and add cocktail table reference.",
      dueDate: "2026-06-21",
      status: "To Do",
      priority: "Medium",
      checklist: [],
    },
    {
      id: "task-rivera-rentals",
      organizationId: "org-coco-cabana",
      projectId: "project-rivera-shower",
      eventId: "event-rivera-shower",
      ownerId: "user-planner-maya",
      title: "Confirm rental quantities",
      description: "Finalize chair, linen, parasol, and glassware counts.",
      dueDate: "2026-06-24",
      status: "To Do",
      priority: "High",
      checklist: [],
    },
    {
      id: "task-chen-sponsor-wall",
      organizationId: "org-coco-cabana",
      projectId: "project-chen-gala",
      eventId: "event-chen-gala",
      ownerId: "user-admin-ava",
      title: "Approve sponsor wall fabrication",
      description: "Review logo layout and confirm production timeline.",
      dueDate: "2026-06-19",
      status: "In Progress",
      priority: "High",
      checklist: [],
    },
    {
      id: "task-chen-runshow",
      organizationId: "org-coco-cabana",
      projectId: "project-chen-gala",
      eventId: "event-chen-gala",
      ownerId: "user-planner-maya",
      title: "Draft production run-of-show",
      description: "Include auction, sponsor remarks, and entertainment cues.",
      dueDate: "2026-06-26",
      status: "To Do",
      priority: "Medium",
      checklist: [],
    },
    {
      id: "task-morrison-summary",
      organizationId: "org-coco-cabana",
      projectId: "project-morrison-baby",
      eventId: "event-morrison-baby",
      ownerId: "user-planner-maya",
      title: "Write post-event summary",
      description: "Capture wins, issues, referrals, and budget performance.",
      dueDate: "2026-06-03",
      status: "Done",
      priority: "Low",
      checklist: [],
    },
  ],
  taskWorkflowColumns: [
    {
      id: "task-column-backlog",
      organizationId: "org-coco-cabana",
      name: "Backlog",
      normalizedStatus: "Not Started",
      mappedTaskStatus: "To Do",
      sortOrder: 10,
      isDefault: true,
      isArchived: false,
      metadata: { seeded: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-column-todo",
      organizationId: "org-coco-cabana",
      name: "To Do",
      normalizedStatus: "Not Started",
      mappedTaskStatus: "To Do",
      sortOrder: 20,
      isDefault: true,
      isArchived: false,
      metadata: { seeded: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-column-progress",
      organizationId: "org-coco-cabana",
      name: "In Progress",
      normalizedStatus: "Active",
      mappedTaskStatus: "In Progress",
      sortOrder: 30,
      isDefault: true,
      isArchived: false,
      metadata: { seeded: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-column-waiting",
      organizationId: "org-coco-cabana",
      name: "Waiting",
      normalizedStatus: "Waiting",
      mappedTaskStatus: "To Do",
      sortOrder: 40,
      isDefault: true,
      isArchived: false,
      metadata: { seeded: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-column-blocked",
      organizationId: "org-coco-cabana",
      name: "Blocked",
      normalizedStatus: "Blocked",
      mappedTaskStatus: "Blocked",
      sortOrder: 50,
      isDefault: true,
      isArchived: false,
      metadata: { seeded: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-column-done",
      organizationId: "org-coco-cabana",
      name: "Done",
      normalizedStatus: "Completed",
      mappedTaskStatus: "Done",
      sortOrder: 60,
      isDefault: true,
      isArchived: false,
      metadata: { seeded: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  taskLabels: [
    {
      id: "task-label-client",
      organizationId: "org-coco-cabana",
      name: "Client",
      color: "#c9972b",
      description: "Needs client-facing coordination.",
      isActive: true,
      sortOrder: 10,
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-label-vendor",
      organizationId: "org-coco-cabana",
      name: "Vendor",
      color: "#0f766e",
      description: "Requires vendor follow-up.",
      isActive: true,
      sortOrder: 20,
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-label-event-day",
      organizationId: "org-coco-cabana",
      name: "Event Day",
      color: "#dc2626",
      description: "Impacts event-day execution.",
      isActive: true,
      sortOrder: 30,
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-label-finance",
      organizationId: "org-coco-cabana",
      name: "Finance",
      color: "#2563eb",
      description: "Budget, invoice, or expense work.",
      isActive: true,
      sortOrder: 40,
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-label-design",
      organizationId: "org-coco-cabana",
      name: "Design",
      color: "#9333ea",
      description: "Creative or decor decision.",
      isActive: true,
      sortOrder: 50,
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  taskLabelAssignments: [
    {
      id: "task-label-assignment-patel-budget-finance",
      organizationId: "org-coco-cabana",
      taskId: "task-patel-budget",
      labelId: "task-label-finance",
      createdById: "user-admin-ava",
      createdAt: "2026-06-09T14:20:00Z",
    },
    {
      id: "task-label-assignment-patel-call-vendor",
      organizationId: "org-coco-cabana",
      taskId: "task-patel-vendor-call",
      labelId: "task-label-vendor",
      createdById: "user-planner-maya",
      createdAt: "2026-06-09T15:00:00Z",
    },
    {
      id: "task-label-assignment-rivera-moodboard-design",
      organizationId: "org-coco-cabana",
      taskId: "task-rivera-moodboard",
      labelId: "task-label-design",
      createdById: "user-planner-maya",
      createdAt: "2026-06-12T10:15:00Z",
    },
    {
      id: "task-label-assignment-chen-runshow-event-day",
      organizationId: "org-coco-cabana",
      taskId: "task-chen-runshow",
      labelId: "task-label-event-day",
      createdById: "user-planner-maya",
      createdAt: "2026-06-13T12:00:00Z",
    },
  ],
  taskParticipants: [
    {
      id: "task-participant-patel-budget-maya",
      organizationId: "org-coco-cabana",
      taskId: "task-patel-budget",
      userId: "user-planner-maya",
      participantRole: "Assignee",
      addedById: "user-admin-ava",
      createdAt: "2026-06-09T14:20:00Z",
    },
    {
      id: "task-participant-patel-budget-ava-watch",
      organizationId: "org-coco-cabana",
      taskId: "task-patel-budget",
      userId: "user-admin-ava",
      participantRole: "Watcher",
      addedById: "user-admin-ava",
      createdAt: "2026-06-09T14:20:00Z",
    },
    {
      id: "task-participant-rivera-moodboard-ava-watch",
      organizationId: "org-coco-cabana",
      taskId: "task-rivera-moodboard",
      userId: "user-admin-ava",
      participantRole: "Watcher",
      addedById: "user-planner-maya",
      createdAt: "2026-06-12T10:15:00Z",
    },
  ],
  taskChecklists: [
    {
      id: "task-checklist-patel-budget-default",
      organizationId: "org-coco-cabana",
      taskId: "task-patel-budget",
      title: "Approval packet",
      sortOrder: 10,
      createdById: "user-admin-ava",
      metadata: { seeded: true },
      createdAt: "2026-06-09T14:20:00Z",
      updatedAt: "2026-06-09T14:20:00Z",
    },
  ],
  taskSavedViews: [
    {
      id: "task-view-my-overdue",
      organizationId: "org-coco-cabana",
      userId: "user-admin-ava",
      name: "My Overdue Work",
      scope: "private",
      viewType: "table",
      filters: { dueState: "overdue", owner: "me" },
      sort: { field: "dueDate", direction: "asc" },
      isDefault: false,
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "task-view-waiting-on-client",
      organizationId: "org-coco-cabana",
      name: "Waiting on Client",
      scope: "team",
      viewType: "board",
      filters: { normalizedStatus: "Waiting", label: "Client" },
      sort: { field: "position", direction: "asc" },
      isDefault: false,
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  taskInboxItems: [
    {
      id: "task-inbox-fathom-patel-action",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      eventId: "event-patel-sangeet",
      sourceType: "Fathom Action Item",
      sourceTable: "meeting_notes",
      sourceRecordId: "meeting-note-patel-production",
      capturedById: "user-planner-maya",
      capturedAt: "2026-06-12T16:20:00Z",
      rawContent: "Confirm late-night snack station vendor quote.",
      summary: "Confirm late-night snack station vendor quote.",
      suggestedProjectId: "project-patel-sangeet",
      suggestedTitle: "Confirm late-night snack station vendor quote",
      suggestedOwnerId: "user-planner-maya",
      suggestedDueAt: "2026-06-18T17:00:00Z",
      suggestedStatus: "To Do",
      status: "New",
      metadata: { ai_suggested: true },
      createdAt: "2026-06-12T16:20:00Z",
      updatedAt: "2026-06-12T16:20:00Z",
    },
  ],
  invoicePayments: [
    {
      id: "invoice-payment-patel-deposit",
      organizationId: "org-coco-cabana",
      invoiceId: "invoice-patel-deposit",
      projectId: "project-patel-sangeet",
      eventId: "event-patel-sangeet",
      amount: 12000,
      paymentMethod: "Card",
      paidAt: "2026-06-12T15:45:00Z",
      reference: "pi_demo_patel_deposit",
      note: "Deposit captured through demo Stripe flow.",
      recordedById: "user-admin-ava",
      idempotencyKey: "demo-patel-deposit",
      metadata: { source: "demo" },
      createdAt: "2026-06-12T15:45:00Z",
    },
    {
      id: "invoice-payment-chen-deposit",
      organizationId: "org-coco-cabana",
      invoiceId: "invoice-chen-deposit",
      projectId: "project-chen-gala",
      eventId: "event-chen-gala",
      amount: 36750,
      paymentMethod: "Bank Transfer",
      paidAt: "2026-06-18T11:30:00Z",
      reference: "EFT-CHEN-0618",
      note: "Offline deposit recorded by Ava.",
      recordedById: "user-admin-ava",
      idempotencyKey: "demo-chen-deposit",
      metadata: { source: "demo" },
      createdAt: "2026-06-18T11:30:00Z",
    },
  ],
  financeSettings: [
    {
      id: "finance-settings-coco-cabana",
      organizationId: "org-coco-cabana",
      defaultCurrency: "CAD",
      fiscalYearStartMonth: 1,
      requireExpenseApproval: true,
      defaultMarginTargetPercent: 32,
      receiptRequiredThreshold: 250,
      enabledPaymentMethods: ["Card", "Bank Transfer", "ACH", "Zelle", "Cash", "Check", "Other"],
      taxDisplayPreference: "Separate",
      clientFinancialVisibility: "Invoices Only",
      defaultReportDateBasis: "Accrual",
      metadata: { source: "demo" },
      createdAt: "2026-06-19T10:00:00Z",
      updatedAt: "2026-06-19T10:00:00Z",
    },
  ],
  expenses: [
    {
      id: "expense-patel-floral-deposit",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      eventId: "event-patel-sangeet",
      vendorId: "vendor-bloom-haven",
      budgetItemId: "budget-patel-florals",
      createdById: "user-admin-ava",
      approvedById: "user-admin-ava",
      expenseNumber: "EXP-20260612-FLORAL",
      description: "Bloom Haven floral production deposit",
      category: "Florals",
      source: "Vendor Bill",
      status: "Partially Paid",
      currency: "CAD",
      subtotal: 7600,
      taxAmount: 600,
      serviceFeeAmount: 0,
      tipAmount: 0,
      totalAmount: 8200,
      expenseDate: "2026-06-12",
      dueDate: "2026-06-18",
      approvedAt: "2026-06-12T18:00:00Z",
      notes: "Final floral balance due after stem count confirmation.",
      paymentReference: "BLOOM-0612",
      clientBillable: false,
      reimbursable: false,
      bookkeepingStatus: "Reviewed",
      metadata: { source: "demo" },
      idempotencyKey: "demo-expense-patel-floral",
      createdAt: "2026-06-12T18:00:00Z",
      updatedAt: "2026-06-12T18:00:00Z",
    },
    {
      id: "expense-patel-catering-progress",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      eventId: "event-patel-sangeet",
      vendorId: "vendor-saffron-table",
      budgetItemId: "budget-patel-catering",
      createdById: "user-planner-maya",
      approvedById: "user-admin-ava",
      expenseNumber: "EXP-20260614-CATERING",
      description: "Saffron Table catering progress invoice",
      category: "Catering",
      source: "Vendor Bill",
      status: "Approved",
      currency: "CAD",
      subtotal: 13850,
      taxAmount: 650,
      serviceFeeAmount: 0,
      tipAmount: 0,
      totalAmount: 14500,
      expenseDate: "2026-06-14",
      dueDate: "2026-06-24",
      approvedAt: "2026-06-15T13:20:00Z",
      notes: "Includes late-night dosa station hold.",
      clientBillable: false,
      reimbursable: false,
      bookkeepingStatus: "Unreviewed",
      metadata: { source: "demo" },
      idempotencyKey: "demo-expense-patel-catering",
      createdAt: "2026-06-14T18:45:00Z",
      updatedAt: "2026-06-15T13:20:00Z",
    },
    {
      id: "expense-rivera-rental-deposit",
      organizationId: "org-coco-cabana",
      projectId: "project-rivera-shower",
      eventId: "event-rivera-shower",
      vendorId: "vendor-luxe-linen",
      budgetItemId: "budget-rivera-rentals",
      createdById: "user-planner-maya",
      approvedById: "user-planner-maya",
      expenseNumber: "EXP-20260616-RENTAL",
      description: "Luxe Linen rental deposit",
      category: "Rentals",
      source: "Vendor Bill",
      status: "Partially Paid",
      currency: "CAD",
      subtotal: 3600,
      taxAmount: 200,
      serviceFeeAmount: 0,
      tipAmount: 0,
      totalAmount: 3800,
      expenseDate: "2026-06-16",
      dueDate: "2026-07-01",
      approvedAt: "2026-06-16T17:30:00Z",
      notes: "Remaining rental balance due one week before event.",
      clientBillable: false,
      reimbursable: false,
      bookkeepingStatus: "Reviewed",
      metadata: { source: "demo" },
      idempotencyKey: "demo-expense-rivera-rental",
      createdAt: "2026-06-16T17:30:00Z",
      updatedAt: "2026-06-16T17:30:00Z",
    },
  ],
  expensePayments: [
    {
      id: "expense-payment-patel-floral",
      organizationId: "org-coco-cabana",
      expenseId: "expense-patel-floral-deposit",
      amount: 3500,
      currency: "CAD",
      paymentMethod: "Bank Transfer",
      paymentDate: "2026-06-13",
      reference: "EFT-BLOOM-0613",
      notes: "Initial floral deposit paid.",
      recordedById: "user-admin-ava",
      status: "Completed",
      metadata: { source: "demo" },
      idempotencyKey: "demo-expense-payment-patel-floral",
      createdAt: "2026-06-13T12:00:00Z",
      updatedAt: "2026-06-13T12:00:00Z",
    },
    {
      id: "expense-payment-rivera-rentals",
      organizationId: "org-coco-cabana",
      expenseId: "expense-rivera-rental-deposit",
      amount: 1900,
      currency: "CAD",
      paymentMethod: "Card",
      paymentDate: "2026-06-16",
      reference: "CARD-LUXE-0616",
      notes: "Rental deposit.",
      recordedById: "user-planner-maya",
      status: "Completed",
      metadata: { source: "demo" },
      idempotencyKey: "demo-expense-payment-rivera-rental",
      createdAt: "2026-06-16T18:00:00Z",
      updatedAt: "2026-06-16T18:00:00Z",
    },
  ],
  expenseFiles: [
    {
      id: "expense-file-patel-floral",
      organizationId: "org-coco-cabana",
      expenseId: "expense-patel-floral-deposit",
      fileId: "file-patel-floral-invoice",
      visibility: "Internal",
      caption: "Bloom Haven invoice and receipt.",
      createdById: "user-admin-ava",
      createdAt: "2026-06-12T18:05:00Z",
    },
  ],
  bookingSettings: [
    {
      id: "booking-settings-coco-cabana",
      organizationId: "org-coco-cabana",
      requireProposalAcceptance: true,
      requireTermsAcceptance: true,
      requireDepositInvoiceIssued: true,
      requireDepositPaid: true,
      requireManualPlannerApproval: false,
      proposalExpirationDays: 14,
      acceptanceStatement:
        "I accept this proposal, the selected options, payment schedule, and terms for this project.",
      metadata: {},
      createdAt: "2026-06-18T10:00:00Z",
      updatedAt: "2026-06-18T10:00:00Z",
    },
  ],
  proposals: [],
  proposalVersions: [],
  proposalLineItems: [],
  proposalPaymentTerms: [],
  proposalResponses: [],
  proposalFiles: [],
  projectBookingApprovals: [],
  approvals: [
    {
      id: "approval-patel-budget",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      type: "Budget",
      title: "Final budget and variance approval",
      description: "Client approval required before we release remaining vendor deposits.",
      status: "Pending",
      dueDate: "2026-06-15",
    },
    {
      id: "approval-patel-timeline",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      type: "Timeline",
      title: "Production timeline",
      description: "Confirm reveal, speeches, entertainment, and late-night station timing.",
      status: "Pending",
      dueDate: "2026-06-16",
    },
    {
      id: "approval-rivera-moodboard",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      type: "Moodboard",
      title: "Garden party moodboard",
      description: "Client requested one linen image change before approval.",
      status: "Changes Requested",
      dueDate: "2026-06-18",
      respondedAt: "2026-06-08T18:30:00Z",
    },
    {
      id: "approval-rivera-proposal",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      type: "Proposal",
      title: "Decor proposal",
      description: "Proposal includes rental, styling, and floral assumptions.",
      status: "Approved",
      dueDate: "2026-06-09",
      respondedAt: "2026-06-07T12:12:00Z",
    },
    {
      id: "approval-chen-budget",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      type: "Budget",
      title: "Gala production budget",
      description: "Finance lead needs approval view by category and vendor.",
      status: "Pending",
      dueDate: "2026-06-22",
    },
    {
      id: "approval-morrison-summary",
      organizationId: "org-coco-cabana",
      eventId: "event-morrison-baby",
      type: "Timeline",
      title: "Post-event recap",
      description: "Sent recap and gallery handoff to client.",
      status: "Approved",
      dueDate: "2026-06-02",
      respondedAt: "2026-06-02T15:20:00Z",
    },
  ],
  files: [
    {
      id: "file-patel-contract",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      uploadedById: "user-admin-ava",
      name: "Patel signed planning agreement.pdf",
      category: "Contracts",
      storagePath: "org-coco-cabana/event-patel-sangeet/contracts/planning-agreement.pdf",
      mimeType: "application/pdf",
      sizeBytes: 410000,
      createdAt: "2026-05-12T15:20:00Z",
    },
    {
      id: "file-patel-inspiration",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      uploadedById: "user-planner-maya",
      name: "Warm modern mandap references.zip",
      category: "Inspiration Images",
      storagePath: "org-coco-cabana/event-patel-sangeet/inspiration/mandap.zip",
      mimeType: "application/zip",
      sizeBytes: 2800000,
      createdAt: "2026-05-18T11:00:00Z",
    },
    {
      id: "file-patel-floral-invoice",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      eventId: "event-patel-sangeet",
      uploadedById: "user-admin-ava",
      name: "Bloom Haven floral invoice.pdf",
      category: "Receipts",
      storagePath:
        "organizations/org-coco-cabana/projects/project-patel-sangeet/expenses/floral-invoice.pdf",
      mimeType: "application/pdf",
      sizeBytes: 245000,
      visibility: "Internal",
      originalFilename: "bloom-haven-floral-invoice.pdf",
      caption: "Vendor invoice linked to floral expense.",
      createdAt: "2026-06-12T18:05:00Z",
    },
    {
      id: "file-rivera-quote",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      uploadedById: "user-planner-maya",
      name: "Luxe Linen quote - Rivera.pdf",
      category: "Vendor Quotes",
      storagePath: "org-coco-cabana/event-rivera-shower/vendor-quotes/luxe-linen.pdf",
      mimeType: "application/pdf",
      sizeBytes: 320000,
      createdAt: "2026-05-30T17:05:00Z",
    },
    {
      id: "file-chen-sponsor",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      uploadedById: "user-admin-ava",
      name: "Sponsor logo package.zip",
      category: "Event Documents",
      storagePath: "org-coco-cabana/event-chen-gala/event-documents/sponsor-logos.zip",
      mimeType: "application/zip",
      sizeBytes: 7200000,
      createdAt: "2026-06-02T13:15:00Z",
    },
    {
      id: "file-morrison-receipt",
      organizationId: "org-coco-cabana",
      eventId: "event-morrison-baby",
      uploadedById: "user-planner-maya",
      name: "Dessert plinth receipt.pdf",
      category: "Receipts",
      storagePath: "org-coco-cabana/event-morrison-baby/receipts/plinth.pdf",
      mimeType: "application/pdf",
      sizeBytes: 180000,
      createdAt: "2026-05-31T10:10:00Z",
    },
  ],
  comments: [
    {
      id: "comment-patel-1",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      authorId: "user-admin-ava",
      body: "Need client confirmation on whether the family wants cold sparks during the grand entrance.",
      visibility: "Internal",
      createdAt: "2026-06-09T12:10:00Z",
    },
    {
      id: "comment-rivera-1",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      authorId: "user-planner-maya",
      body: "Client prefers a softer blush linen and wants the dessert table to feel less formal.",
      visibility: "Client",
      createdAt: "2026-06-08T18:35:00Z",
    },
    {
      id: "comment-chen-1",
      organizationId: "org-coco-cabana",
      eventId: "event-chen-gala",
      authorId: "user-admin-ava",
      body: "Finance team asked for a clear explanation of catering variance once final guest count lands.",
      visibility: "Internal",
      createdAt: "2026-06-05T09:55:00Z",
    },
  ],
  communicationThreads: [
    {
      id: "thread-grace-inquiry-ack",
      organizationId: "org-coco-cabana",
      projectId: "project-grace-wilson",
      leadId: "lead-grace-wilson",
      eventId: "",
      assignedToId: "user-planner-maya",
      subject: "Inquiry received: luxury birthday dinner",
      clientName: "Grace Wilson",
      participants: ["grace.wilson@example.com", "planner@cococabana.demo"],
      channel: "Email",
      status: "Waiting on Client",
      integrationSource: "EaseEvents",
      preview: "Auto-acknowledgment sent with consultation booking next step.",
      unreadCount: 0,
      lastActivityAt: "2026-06-01T13:14:00Z",
    },
    {
      id: "thread-jordan-consultation",
      organizationId: "org-coco-cabana",
      projectId: "project-jordan-miles",
      leadId: "lead-jordan-miles",
      eventId: "",
      assignedToId: "user-admin-ava",
      subject: "Consultation prep and venue shortlist",
      clientName: "Jordan Miles",
      participants: ["jordan.miles@example.com", "owner@cococabana.demo"],
      channel: "Meeting",
      status: "Scheduled",
      integrationSource: "Google Calendar",
      preview: "Consultation scheduled to clarify budget guardrails and decor direction.",
      unreadCount: 0,
      lastActivityAt: "2026-06-02T15:30:00Z",
    },
    {
      id: "thread-patel-budget-approval",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      eventId: "event-patel-sangeet",
      assignedToId: "user-admin-ava",
      subject: "Final budget approval + remaining balance timing",
      clientName: "Nisha Patel",
      participants: ["nisha.patel@example.com", "owner@cococabana.demo"],
      channel: "Email",
      status: "Needs Reply",
      integrationSource: "Gmail",
      preview:
        "Client asked whether florals can be split into two payment milestones before approval.",
      unreadCount: 1,
      lastActivityAt: "2026-06-15T16:20:00Z",
    },
    {
      id: "thread-patel-planning-call",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      eventId: "event-patel-sangeet",
      assignedToId: "user-planner-maya",
      subject: "Production planning call recap",
      clientName: "Nisha Patel",
      participants: ["nisha.patel@example.com", "planner@cococabana.demo"],
      channel: "Meeting",
      status: "Waiting on Client",
      integrationSource: "Google Calendar",
      preview:
        "Client recap sent with three confirmations needed on guest count, cold sparks, and late-night station.",
      unreadCount: 0,
      lastActivityAt: "2026-06-14T20:05:00Z",
    },
    {
      id: "thread-rivera-checkin",
      organizationId: "org-coco-cabana",
      projectId: "project-rivera-shower",
      eventId: "event-rivera-shower",
      assignedToId: "user-planner-maya",
      subject: "Garden shower style check-in",
      clientName: "Sofia Rivera",
      participants: ["sofia@example.com", "planner@cococabana.demo"],
      channel: "Phone",
      status: "Scheduled",
      integrationSource: "Google Meet",
      preview: "Quick design review booked for revised moodboard and rentals count.",
      unreadCount: 0,
      lastActivityAt: "2026-06-16T09:15:00Z",
    },
  ],
  communicationMessages: [
    {
      id: "message-grace-inquiry-ack-1",
      organizationId: "org-coco-cabana",
      projectId: "project-grace-wilson",
      leadId: "lead-grace-wilson",
      threadId: "thread-grace-inquiry-ack",
      eventId: "",
      authorId: "user-planner-maya",
      direction: "Outbound",
      body: "Hi Grace, thank you for reaching out to Coco Cabana Events about your luxury birthday dinner. We received your inquiry and will review the details shortly. You can book a consultation from the link in this message when you are ready.",
      summary: "Inquiry acknowledgment sent.",
      visibility: "Client",
      sentAt: "2026-06-01T13:14:00Z",
    },
    {
      id: "message-jordan-consultation-1",
      organizationId: "org-coco-cabana",
      projectId: "project-jordan-miles",
      leadId: "lead-jordan-miles",
      threadId: "thread-jordan-consultation",
      eventId: "",
      authorId: "user-admin-ava",
      direction: "Internal",
      body: "Prep call notes: Jordan has venue options shortlisted and wants a clearer decor package recommendation before proposal.",
      summary: "Consultation prep note captured.",
      visibility: "Internal",
      sentAt: "2026-06-02T15:30:00Z",
    },
    {
      id: "message-patel-budget-1",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      threadId: "thread-patel-budget-approval",
      eventId: "event-patel-sangeet",
      authorId: "user-admin-ava",
      direction: "Outbound",
      body: "Attached the updated category summary and vendor payment schedule. Let us know if you want us to break florals into separate milestones.",
      summary: "Sent updated budget approval packet.",
      visibility: "Client",
      sentAt: "2026-06-14T14:05:00Z",
    },
    {
      id: "message-patel-budget-2",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      threadId: "thread-patel-budget-approval",
      eventId: "event-patel-sangeet",
      direction: "Inbound",
      body: "Can we split the floral payment into two dates and review the late-night station headcount before I approve?",
      summary: "Client requested milestone split and catering review.",
      visibility: "Client",
      sentAt: "2026-06-15T16:20:00Z",
    },
    {
      id: "message-patel-call-1",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      threadId: "thread-patel-planning-call",
      eventId: "event-patel-sangeet",
      authorId: "user-planner-maya",
      direction: "Internal",
      body: "Recap drafted after planning call. Action items: finalize guest count, confirm cold sparks, and approve revised catering headcount.",
      summary: "Internal recap with action items.",
      visibility: "Internal",
      sentAt: "2026-06-14T18:40:00Z",
    },
    {
      id: "message-rivera-checkin-1",
      organizationId: "org-coco-cabana",
      projectId: "project-rivera-shower",
      threadId: "thread-rivera-checkin",
      eventId: "event-rivera-shower",
      authorId: "user-planner-maya",
      direction: "Outbound",
      body: "Booked a 20-minute design review to walk through the updated linen option and parasol count.",
      summary: "Call scheduled and confirmation sent.",
      visibility: "Client",
      sentAt: "2026-06-16T09:15:00Z",
    },
  ],
  meetings: [
    {
      id: "meeting-patel-production",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      leadId: "lead-nisha-patel",
      eventId: "event-patel-sangeet",
      title: "Production planning call",
      meetingType: "Google Meet",
      status: "Completed",
      startAt: "2026-06-14T17:00:00Z",
      endAt: "2026-06-14T17:45:00Z",
      organizerId: "user-planner-maya",
      attendees: ["Nisha Patel", "Ava Montero", "Maya Singh"],
      agenda:
        "Review run-of-show, guest count assumptions, entertainment cues, and budget approvals.",
      link: "https://meet.google.com/new",
      transcript:
        "Client wants one more review on guest count, requested pricing clarity on florals, and asked if cold sparks fit venue policy.",
      internalSummary:
        "Strong alignment on event look and feel. Blockers are cold sparks approval, final guest count, and revised catering commitment.",
      clientSummary:
        "We reviewed the event flow, budget, and next approvals. We will send a revised floral/payment summary and confirm venue guidance on cold sparks.",
      notes:
        "Family is comfortable with late-night station, but wants final guest count reviewed before sign-off.",
      actionItems: [
        {
          id: "meeting-patel-action-1",
          title: "Send revised floral payment milestone breakdown",
          ownerId: "user-admin-ava",
          dueDate: "2026-06-16",
          taskId: "task-patel-budget",
          isComplete: false,
        },
        {
          id: "meeting-patel-action-2",
          title: "Confirm venue policy on cold sparks",
          ownerId: "user-planner-maya",
          dueDate: "2026-06-17",
          taskId: "task-patel-floorplan",
          isComplete: false,
        },
      ],
      createdAt: "2026-06-14T17:50:00Z",
    },
    {
      id: "meeting-rivera-design",
      organizationId: "org-coco-cabana",
      projectId: "project-rivera-shower",
      eventId: "event-rivera-shower",
      title: "Design check-in",
      meetingType: "Google Meet",
      status: "Scheduled",
      startAt: "2026-06-18T15:00:00Z",
      endAt: "2026-06-18T15:20:00Z",
      organizerId: "user-planner-maya",
      attendees: ["Sofia Rivera", "Maya Singh"],
      agenda: "Review updated moodboard, rentals quantity, and table styling direction.",
      link: "https://meet.google.com/new",
      transcript: "",
      internalSummary: "",
      clientSummary: "",
      notes: "Prepare updated blush linen option before meeting.",
      actionItems: [],
      createdAt: "2026-06-16T09:15:00Z",
    },
  ],
  projectInspirationLinks: [
    {
      id: "inspiration-grace-pinterest",
      organizationId: "org-coco-cabana",
      projectId: "project-grace-wilson",
      leadId: "lead-grace-wilson",
      label: "Pinterest lounge board",
      url: "https://www.pinterest.com/search/pins/?q=tropical%20luxury%20birthday%20dinner",
      createdById: "user-planner-maya",
      createdAt: "2026-06-01T13:12:00Z",
      updatedAt: "2026-06-01T13:12:00Z",
    },
    {
      id: "inspiration-grace-champagne",
      organizationId: "org-coco-cabana",
      projectId: "project-grace-wilson",
      leadId: "lead-grace-wilson",
      label: "Champagne wall reference",
      url: "https://example.com/inspiration/champagne-wall",
      createdById: "user-planner-maya",
      createdAt: "2026-06-01T13:12:30Z",
      updatedAt: "2026-06-01T13:12:30Z",
    },
  ],
  taskLinks: [
    {
      id: "task-link-patel-budget-packet",
      organizationId: "org-coco-cabana",
      taskId: "task-patel-budget",
      label: "Budget packet draft",
      url: "https://drive.google.com/example-budget-packet",
      createdById: "user-admin-ava",
      createdAt: "2026-06-09T14:20:00Z",
    },
    {
      id: "task-link-rivera-moodboard",
      organizationId: "org-coco-cabana",
      taskId: "task-rivera-moodboard",
      label: "Moodboard reference",
      url: "https://pinterest.com/example-rivera-moodboard",
      createdById: "user-planner-maya",
      createdAt: "2026-06-12T10:15:00Z",
    },
  ],
  taskAttachments: [],
  emailTemplates: [
    {
      id: "template-email-inquiry-ack",
      organizationId: "org-coco-cabana",
      name: "Inquiry acknowledgment",
      templateType: "inquiry_acknowledgment",
      subject: "We received your {{event_type}} inquiry",
      body: "Hi {{client_name}},\n\nThank you for reaching out to {{organization_name}} about your {{event_type}}. We received your inquiry for {{event_date}} and will review the details shortly. {{consultation_link}}\n\nOur team can help with planning, decor, vendor coordination, budgets, approvals, and day-of execution.\n\nWarmly,\n{{organization_name}}",
      isActive: true,
      isDefault: true,
      metadata: { seeded: true },
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "template-email-proposal",
      organizationId: "org-coco-cabana",
      name: "Proposal sent",
      templateType: "proposal_sent",
      subject: "Your {{event_type}} proposal is ready",
      body: "Hi {{client_name}},\n\nYour proposal is ready for review. Please send any questions or changes so we can keep your {{event_date}} planning timeline moving.\n\nWarmly,\n{{planner_name}}",
      isActive: true,
      isDefault: true,
      metadata: { seeded: true },
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:05:00Z",
      updatedAt: "2026-06-01T10:05:00Z",
    },
  ],
  projectActivityEvents: [
    {
      id: "activity-grace-project-created",
      organizationId: "org-coco-cabana",
      projectId: "project-grace-wilson",
      actorId: "user-planner-maya",
      activityType: "system",
      title: "Inquiry workspace created",
      body: "Lead, client profile, communication thread, and inspiration links are connected.",
      metadata: { source: "Instagram" },
      createdAt: "2026-06-01T13:10:00Z",
    },
    {
      id: "activity-patel-converted",
      organizationId: "org-coco-cabana",
      projectId: "project-patel-sangeet",
      actorId: "user-admin-ava",
      activityType: "status",
      title: "Lead converted to booked event",
      body: "Original inquiry history remains in the project workspace.",
      metadata: { lead_id: "lead-nisha-patel", event_id: "event-patel-sangeet" },
      createdAt: "2026-05-12T12:00:00Z",
    },
  ],
  projectReminders: [
    {
      id: "reminder-grace-follow-up",
      organizationId: "org-coco-cabana",
      projectId: "project-grace-wilson",
      assignedToId: "user-planner-maya",
      title: "Follow up if Grace has not booked a consultation",
      dueAt: "2026-06-03T13:10:00Z",
      status: "Open",
      automationSource: "inquiry_acknowledgment",
      metadata: { lead_id: "lead-grace-wilson" },
      createdAt: "2026-06-01T13:10:00Z",
      updatedAt: "2026-06-01T13:10:00Z",
    },
  ],
  workflowAutomations: [
    {
      id: "automation-inquiry-follow-up",
      organizationId: "org-coco-cabana",
      name: "Inquiry follow-up reminder",
      description:
        "Notify the project owner and create a follow-up reminder when a new inquiry lands.",
      triggerType: "inquiry_created",
      status: "Inactive",
      conditions: [],
      approvalPolicy: "automatic",
      quietHours: {},
      cooldownMinutes: 0,
      priority: 10,
      metadata: { preset_key: "inquiry_follow_up", seeded: true },
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "automation-event-day-readiness",
      organizationId: "org-coco-cabana",
      name: "Event-day readiness check",
      description:
        "Surface run-of-show, vendor arrival, payment, and issue-readiness actions before event day.",
      triggerType: "event_day_readiness_due",
      status: "Inactive",
      conditions: [],
      approvalPolicy: "automatic",
      quietHours: {},
      cooldownMinutes: 0,
      priority: 50,
      metadata: { preset_key: "event_day_readiness", seeded: true },
      createdById: "user-admin-ava",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  workflowAutomationActions: [
    {
      id: "automation-action-inquiry-notification",
      organizationId: "org-coco-cabana",
      automationId: "automation-inquiry-follow-up",
      actionType: "send_in_app_notification",
      name: "Notify project owner",
      config: {
        recipient: "project_owner",
        severity: "Warning",
        title: "New inquiry needs qualification",
        body: "Review budget, guest count, inspiration, and consultation readiness.",
      },
      requiresApproval: false,
      sortOrder: 10,
      isActive: true,
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "automation-action-inquiry-reminder",
      organizationId: "org-coco-cabana",
      automationId: "automation-inquiry-follow-up",
      actionType: "create_reminder",
      name: "Create inquiry follow-up reminder",
      config: { title: "Follow up on new inquiry", delay_hours: 24, assign_to: "project_owner" },
      requiresApproval: false,
      sortOrder: 20,
      isActive: true,
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "automation-action-event-day-notification",
      organizationId: "org-coco-cabana",
      automationId: "automation-event-day-readiness",
      actionType: "send_in_app_notification",
      name: "Event-day readiness alert",
      config: {
        recipient: "project_owner",
        severity: "Warning",
        title: "Event-day readiness check due",
        body: "Review run-of-show, vendor status, payments, and open issues.",
      },
      requiresApproval: false,
      sortOrder: 10,
      isActive: true,
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  workflowEvents: [
    {
      id: "workflow-event-demo-inquiry",
      organizationId: "org-coco-cabana",
      projectId: "project-grace-wilson",
      leadId: "lead-grace-wilson",
      eventType: "inquiry_created",
      status: "Processed",
      payload: { source: "Instagram" },
      dedupeKey: "demo-inquiry-created-lead-grace-wilson",
      occurredAt: "2026-06-01T13:10:00Z",
      processedAt: "2026-06-01T13:11:00Z",
      createdAt: "2026-06-01T13:10:00Z",
    },
  ],
  workflowExecutions: [
    {
      id: "workflow-execution-demo-inquiry",
      organizationId: "org-coco-cabana",
      automationId: "automation-inquiry-follow-up",
      workflowEventId: "workflow-event-demo-inquiry",
      projectId: "project-grace-wilson",
      status: "Completed",
      scheduledFor: "2026-06-01T13:10:30Z",
      startedAt: "2026-06-01T13:10:30Z",
      completedAt: "2026-06-01T13:10:31Z",
      attemptCount: 1,
      idempotencyKey: "demo-inquiry-follow-up-lead-grace-wilson",
      metadata: { demo: true },
      createdAt: "2026-06-01T13:10:30Z",
      updatedAt: "2026-06-01T13:10:31Z",
    },
  ],
  workflowActionRuns: [
    {
      id: "workflow-action-run-demo-inquiry",
      organizationId: "org-coco-cabana",
      executionId: "workflow-execution-demo-inquiry",
      automationActionId: "automation-action-inquiry-notification",
      actionType: "send_in_app_notification",
      status: "Completed",
      startedAt: "2026-06-01T13:10:30Z",
      completedAt: "2026-06-01T13:10:31Z",
      output: { notification_id: "notification-demo-inquiry" },
      idempotencyKey: "demo-inquiry-follow-up-lead-grace-wilson-notification",
      createdAt: "2026-06-01T13:10:30Z",
      updatedAt: "2026-06-01T13:10:31Z",
    },
  ],
  notifications: [
    {
      id: "notification-demo-inquiry",
      organizationId: "org-coco-cabana",
      recipientUserId: "user-planner-maya",
      projectId: "project-grace-wilson",
      workflowExecutionId: "workflow-execution-demo-inquiry",
      notificationType: "inquiry_created",
      severity: "Warning",
      status: "Unread",
      title: "New inquiry needs qualification",
      body: "Review budget, guest count, inspiration, and consultation readiness.",
      href: "/ease-events/leads/lead-grace-wilson",
      channel: "in_app",
      actionRequired: true,
      dedupeKey: "demo-notification-inquiry-lead-grace-wilson",
      metadata: { demo: true },
      createdAt: "2026-06-01T13:10:31Z",
      updatedAt: "2026-06-01T13:10:31Z",
    },
  ],
  notificationPreferences: [],
  closeoutSettings: [
    {
      id: "closeout-settings-coco-cabana",
      organizationId: "org-coco-cabana",
      closeoutDueDays: 7,
      requireVendorReviews: true,
      requireInternalRetrospective: true,
      requireFeedbackRequest: false,
      requireFinancialReview: true,
      publicReviewRequestsEnabled: false,
      defaultRetentionPolicy: {},
      metadata: { seeded: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  postEventCloseouts: [],
  postEventCloseoutItems: [],
  finalDeliverables: [],
  clientFeedbackResponses: [],
  clientConsents: [],
  vendorPerformanceReviews: [],
  internalRetrospectives: [],
  closeoutFinancialSnapshots: [],
  retentionSettings: [
    {
      id: "retention-settings-coco-cabana",
      organizationId: "org-coco-cabana",
      jurisdictionProfile: "Manual Review",
      promotionalOutreachEnabled: false,
      expressConsentRequired: true,
      impliedConsentTrackingEnabled: false,
      consentReviewDays: 365,
      referralOutreachPolicy: "review_required",
      quietHours: { start: "20:00", end: "08:00" },
      defaultExecutionMode: "draft_only",
      defaultRetentionDays: 730,
      manualComplianceReview: true,
      metadata: { seeded: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  clientMilestones: [
    {
      id: "milestone-morrison-shower",
      organizationId: "org-coco-cabana",
      clientId: "client-priya-morrison",
      sourceProjectId: "project-morrison-baby",
      milestoneType: "Event Anniversary",
      title: "Morrison baby shower anniversary",
      milestoneDate: "2027-05-30",
      month: 5,
      day: 30,
      recurrenceRule: "FREQ=YEARLY",
      reminderOffsetDays: 60,
      nextOccurrenceDate: "2027-05-30",
      sensitivity: "Standard",
      source: "Planner confirmed",
      isActive: true,
      notes: "Review family milestone follow-up two months before the anniversary.",
      idempotencyKey: "demo-milestone-morrison-shower",
      metadata: { demo: true },
      createdById: "user-planner-maya",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  rebookingOpportunities: [
    {
      id: "rebooking-morrison-milestone",
      organizationId: "org-coco-cabana",
      clientId: "client-priya-morrison",
      sourceProjectId: "project-morrison-baby",
      sourceEventId: "event-morrison-baby",
      sourceMilestoneId: "milestone-morrison-shower",
      assignedToId: "user-planner-maya",
      opportunityType: "Anniversary",
      title: "Priya family milestone follow-up",
      description:
        "Personal follow-up only; confirm whether the client wants help with the next family celebration before creating a lead.",
      stage: "Review Required",
      estimatedEventDate: "2027-05-30",
      targetContactDate: "2027-03-31",
      estimatedValue: 8500,
      estimatedProbability: 35,
      eventType: "Family milestone celebration",
      preferredContactChannel: "Email",
      consentStatusSnapshot: "Manual Review",
      nextAction: "Confirm interest before drafting outreach.",
      nextActionAt: "2027-03-31T14:00:00Z",
      aiSummary:
        "AI-generated draft placeholder: review prior baby shower preferences, guest count, and referral notes before contacting.",
      aiSummaryGeneratedAt: "2026-06-01T10:00:00Z",
      idempotencyKey: "demo-rebooking-morrison-milestone",
      metadata: { demo: true },
      createdById: "user-planner-maya",
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  clientReferralLinks: [
    {
      id: "referral-link-morrison",
      organizationId: "org-coco-cabana",
      clientId: "client-priya-morrison",
      projectId: "project-morrison-baby",
      referralCode: "PRIYA-DEMO",
      sourceCampaign: "Demo referral",
      isActive: true,
      createdById: "user-planner-maya",
      metadata: { demo: true },
      createdAt: "2026-06-01T10:00:00Z",
      updatedAt: "2026-06-01T10:00:00Z",
    },
  ],
  referrals: [],
  communicationEligibilityLogs: [],
  timelineItems: [
    {
      id: "timeline-patel-load-in",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      title: "Vendor load-in opens",
      description: "Rentals, florals, AV, and decor teams can begin dock access.",
      startTime: "08:00",
      endTime: "08:30",
      ownerId: "user-planner-maya",
      status: "Ready",
      location: "Venue loading dock",
      visibility: "Internal",
      sortOrder: 10,
      createdAt: "2026-06-10T12:00:00Z",
    },
    {
      id: "timeline-patel-floral-install",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      title: "Mandap and reception florals complete",
      description: "Final floral placement before photo/video captures room details.",
      startTime: "11:30",
      endTime: "13:00",
      ownerId: "user-planner-maya",
      dependsOnItemId: "timeline-patel-load-in",
      status: "Planned",
      location: "Main ballroom",
      visibility: "Internal",
      sortOrder: 20,
      createdAt: "2026-06-10T12:05:00Z",
    },
    {
      id: "timeline-patel-client-reveal",
      organizationId: "org-coco-cabana",
      eventId: "event-patel-sangeet",
      title: "Client reveal",
      description: "Walk Nisha and family through the room before guest arrival.",
      startTime: "16:15",
      endTime: "16:35",
      ownerId: "user-admin-ava",
      dependsOnItemId: "timeline-patel-floral-install",
      status: "Planned",
      location: "Main ballroom",
      visibility: "Client",
      sortOrder: 30,
      createdAt: "2026-06-10T12:10:00Z",
    },
    {
      id: "timeline-rivera-florals",
      organizationId: "org-coco-cabana",
      eventId: "event-rivera-shower",
      title: "Garden tablescape install",
      description: "Complete linen, parasol, floral, and dessert table styling.",
      startTime: "09:30",
      endTime: "11:00",
      ownerId: "user-planner-maya",
      status: "Ready",
      location: "Garden terrace",
      visibility: "Internal",
      sortOrder: 10,
      createdAt: "2026-06-11T10:00:00Z",
    },
  ],
  timelineVersions: [],
  eventDaySessions: [],
  eventDayVendorStatuses: [],
  eventDayIssues: [],
  eventTemplates: [
    {
      id: "template-luxury-birthday",
      organizationId: "org-coco-cabana",
      name: "Luxury Birthday",
      eventType: "Birthday celebration",
      description: "Dinner party, statement decor, dessert moment, rentals, and entertainment.",
      defaultGuestCount: 100,
      defaultClientPrice: 18000,
      timelineNotes: "Load-in, decor install, client reveal, guest arrival, cake moment, strike.",
      internalNotes: "Confirm venue access, cake handling, entertainment power, and dance floor.",
      isActive: true,
      createdAt: "2026-06-01T10:00:00Z",
    },
    {
      id: "template-wedding-celebration",
      organizationId: "org-coco-cabana",
      name: "Wedding Celebration",
      eventType: "Wedding celebration",
      description:
        "Multi-vendor celebration with approvals, florals, rentals, and production cues.",
      defaultGuestCount: 220,
      defaultClientPrice: 42000,
      timelineNotes: "Vendor load-in, ceremony/reveal, cocktail hour, reception, strike.",
      internalNotes: "Assign one owner to family communication and one owner to vendor timing.",
      isActive: true,
      createdAt: "2026-06-01T10:05:00Z",
    },
  ],
  taskTemplates: [
    {
      id: "task-template-venue-access",
      organizationId: "org-coco-cabana",
      eventTemplateId: "template-luxury-birthday",
      title: "Confirm venue access and load-in rules",
      description:
        "Collect dock access, elevator details, insurance requirements, and setup windows.",
      priority: "High",
      dueOffsetDays: -21,
      checklistItems: ["Load-in window", "Certificate of insurance", "Power access"],
      sortOrder: 10,
    },
    {
      id: "task-template-client-approvals",
      organizationId: "org-coco-cabana",
      eventTemplateId: "template-wedding-celebration",
      title: "Send client approval packet",
      description: "Budget, moodboard, floor plan, and production timeline need client sign-off.",
      priority: "High",
      dueOffsetDays: -14,
      checklistItems: ["Budget", "Moodboard", "Timeline", "Proposal"],
      sortOrder: 10,
    },
  ],
  budgetTemplates: [
    {
      id: "budget-template-birthday-decor",
      organizationId: "org-coco-cabana",
      eventTemplateId: "template-luxury-birthday",
      category: "Decor",
      description: "Statement decor package",
      plannedAmount: 6500,
      marginEstimate: 2500,
      dueOffsetDays: -14,
      sortOrder: 10,
    },
    {
      id: "budget-template-wedding-florals",
      organizationId: "org-coco-cabana",
      eventTemplateId: "template-wedding-celebration",
      category: "Florals",
      description: "Ceremony and reception floral production",
      plannedAmount: 12000,
      marginEstimate: 4200,
      dueOffsetDays: -30,
      sortOrder: 10,
    },
  ],
  approvalTemplates: [
    {
      id: "approval-template-budget",
      organizationId: "org-coco-cabana",
      eventTemplateId: "template-wedding-celebration",
      type: "Budget",
      title: "Budget approval",
      description: "Client signs off on planned spend, vendor deposits, and remaining balance.",
      dueOffsetDays: -21,
      sortOrder: 10,
    },
    {
      id: "approval-template-timeline",
      organizationId: "org-coco-cabana",
      eventTemplateId: "template-luxury-birthday",
      type: "Timeline",
      title: "Run-of-show approval",
      description: "Client confirms key timing, reveal, entertainment, and cake moment.",
      dueOffsetDays: -10,
      sortOrder: 10,
    },
  ],
  vendorTemplates: [
    {
      id: "vendor-template-rentals",
      organizationId: "org-coco-cabana",
      eventTemplateId: "template-luxury-birthday",
      serviceCategory: "Rentals",
      preferredVendorId: "vendor-velvet-rentals",
      notes: "Confirm lounge groupings, dance floor, and delivery access.",
      sortOrder: 10,
    },
    {
      id: "vendor-template-florals",
      organizationId: "org-coco-cabana",
      eventTemplateId: "template-wedding-celebration",
      serviceCategory: "Florals",
      preferredVendorId: "vendor-bloom-room",
      notes: "Use for statement floral builds and mandap/reception transitions.",
      sortOrder: 10,
    },
  ],
};
