/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LogoOptionsRouteImport } from './routes/logo-options'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EaseEventsIndexRouteImport } from './routes/ease-events/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as EaseEventsWorkRouteImport } from './routes/ease-events/work'
import { Route as EaseEventsTasksRouteImport } from './routes/ease-events/tasks'
import { Route as EaseEventsSettingsRouteImport } from './routes/ease-events/settings'
import { Route as EaseEventsRetentionRouteImport } from './routes/ease-events/retention'
import { Route as EaseEventsReportsRouteImport } from './routes/ease-events/reports'
import { Route as EaseEventsLoginRouteImport } from './routes/ease-events/login'
import { Route as EaseEventsInquiryRouteImport } from './routes/ease-events/inquiry'
import { Route as EaseEventsFilesRouteImport } from './routes/ease-events/files'
import { Route as EaseEventsCommunicationsRouteImport } from './routes/ease-events/communications'
import { Route as EaseEventsClientPortalRouteImport } from './routes/ease-events/client-portal'
import { Route as EaseEventsCalendarRouteImport } from './routes/ease-events/calendar'
import { Route as EaseEventsBudgetsRouteImport } from './routes/ease-events/budgets'
import { Route as EaseEventsVendorsIndexRouteImport } from './routes/ease-events/vendors/index'
import { Route as EaseEventsLeadsIndexRouteImport } from './routes/ease-events/leads/index'
import { Route as EaseEventsEventsIndexRouteImport } from './routes/ease-events/events/index'
import { Route as EaseEventsClientsIndexRouteImport } from './routes/ease-events/clients/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as EaseEventsVendorsVendorIdRouteImport } from './routes/ease-events/vendors/$vendorId'
import { Route as EaseEventsProposalsTokenRouteImport } from './routes/ease-events/proposals/$token'
import { Route as EaseEventsLeadsLeadIdRouteImport } from './routes/ease-events/leads/$leadId'
import { Route as EaseEventsEventsEventIdRouteImport } from './routes/ease-events/events/$eventId'
import { Route as EaseEventsClientsClientIdRouteImport } from './routes/ease-events/clients/$clientId'
import { Route as ApiPublicConsultationRouteImport } from './routes/api/public/consultation'
import { Route as ApiEaseEventsPublicInquiryRouteImport } from './routes/api/ease-events/public-inquiry'
import { Route as ApiEaseEventsClientPortalAccessRouteImport } from './routes/api/ease-events/client-portal-access'
import { Route as ApiEaseEventsCheckoutRouteImport } from './routes/api/ease-events/checkout'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as EaseEventsEventsEventIdEventDayRouteImport } from './routes/ease-events/events/$eventId.event-day'
import { Route as ApiEaseEventsPublicInquiryUploadRouteImport } from './routes/api/ease-events/public-inquiry/upload'
import { Route as ApiEaseEventsPublicInquiryFinalizeRouteImport } from './routes/api/ease-events/public-inquiry/finalize'
import { Route as ApiEaseEventsProposalsSendRouteImport } from './routes/api/ease-events/proposals/send'
import { Route as ApiEaseEventsProposalsPaymentRouteImport } from './routes/api/ease-events/proposals/payment'
import { Route as ApiEaseEventsProposalsDraftRouteImport } from './routes/api/ease-events/proposals/draft'
import { Route as ApiEaseEventsProposalsBookingStatusRouteImport } from './routes/api/ease-events/proposals/booking-status'
import { Route as ApiEaseEventsProposalsBookingApprovalRouteImport } from './routes/api/ease-events/proposals/booking-approval'
import { Route as ApiEaseEventsIntegrationsMeetingsRouteImport } from './routes/api/ease-events/integrations/meetings'
import { Route as ApiEaseEventsAiMeetingSummaryRouteImport } from './routes/api/ease-events/ai/meeting-summary'
import { Route as ApiEaseEventsProposalsReviewTokenRouteImport } from './routes/api/ease-events/proposals/review/$token'
import { Route as ApiEaseEventsIntegrationsOauthStartRouteImport } from './routes/api/ease-events/integrations/oauth/start'
import { Route as ApiEaseEventsIntegrationsOauthCallbackRouteImport } from './routes/api/ease-events/integrations/oauth/callback'
import { Route as ApiEaseEventsIntegrationsMailSyncRouteImport } from './routes/api/ease-events/integrations/mail/sync'
import { Route as ApiEaseEventsIntegrationsMailSendRouteImport } from './routes/api/ease-events/integrations/mail/send'
import { Route as ApiEaseEventsIntegrationsFathomSyncRouteImport } from './routes/api/ease-events/integrations/fathom/sync'
import { Route as ApiEaseEventsIntegrationsFathomMeetingsRouteImport } from './routes/api/ease-events/integrations/fathom/meetings'
import { Route as ApiEaseEventsIntegrationsFathomImportRouteImport } from './routes/api/ease-events/integrations/fathom/import'
import { Route as ApiEaseEventsIntegrationsCalendarSyncRouteImport } from './routes/api/ease-events/integrations/calendar/sync'
import { Route as ApiEaseEventsIntegrationsAccountsDisconnectRouteImport } from './routes/api/ease-events/integrations/accounts/disconnect'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoOptionsRoute = LogoOptionsRouteImport.update({
  id: '/logo-options',
  path: '/logo-options',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsIndexRoute = EaseEventsIndexRouteImport.update({
  id: '/ease-events/',
  path: '/ease-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsWorkRoute = EaseEventsWorkRouteImport.update({
  id: '/ease-events/work',
  path: '/ease-events/work',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsTasksRoute = EaseEventsTasksRouteImport.update({
  id: '/ease-events/tasks',
  path: '/ease-events/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsSettingsRoute = EaseEventsSettingsRouteImport.update({
  id: '/ease-events/settings',
  path: '/ease-events/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsRetentionRoute = EaseEventsRetentionRouteImport.update({
  id: '/ease-events/retention',
  path: '/ease-events/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsReportsRoute = EaseEventsReportsRouteImport.update({
  id: '/ease-events/reports',
  path: '/ease-events/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsLoginRoute = EaseEventsLoginRouteImport.update({
  id: '/ease-events/login',
  path: '/ease-events/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsInquiryRoute = EaseEventsInquiryRouteImport.update({
  id: '/ease-events/inquiry',
  path: '/ease-events/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsFilesRoute = EaseEventsFilesRouteImport.update({
  id: '/ease-events/files',
  path: '/ease-events/files',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsCommunicationsRoute =
  EaseEventsCommunicationsRouteImport.update({
    id: '/ease-events/communications',
    path: '/ease-events/communications',
    getParentRoute: () => rootRouteImport,
  } as any)
const EaseEventsClientPortalRoute = EaseEventsClientPortalRouteImport.update({
  id: '/ease-events/client-portal',
  path: '/ease-events/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsCalendarRoute = EaseEventsCalendarRouteImport.update({
  id: '/ease-events/calendar',
  path: '/ease-events/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsBudgetsRoute = EaseEventsBudgetsRouteImport.update({
  id: '/ease-events/budgets',
  path: '/ease-events/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsVendorsIndexRoute = EaseEventsVendorsIndexRouteImport.update({
  id: '/ease-events/vendors/',
  path: '/ease-events/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsLeadsIndexRoute = EaseEventsLeadsIndexRouteImport.update({
  id: '/ease-events/leads/',
  path: '/ease-events/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsEventsIndexRoute = EaseEventsEventsIndexRouteImport.update({
  id: '/ease-events/events/',
  path: '/ease-events/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsClientsIndexRoute = EaseEventsClientsIndexRouteImport.update({
  id: '/ease-events/clients/',
  path: '/ease-events/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsVendorsVendorIdRoute =
  EaseEventsVendorsVendorIdRouteImport.update({
    id: '/ease-events/vendors/$vendorId',
    path: '/ease-events/vendors/$vendorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EaseEventsProposalsTokenRoute =
  EaseEventsProposalsTokenRouteImport.update({
    id: '/ease-events/proposals/$token',
    path: '/ease-events/proposals/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const EaseEventsLeadsLeadIdRoute = EaseEventsLeadsLeadIdRouteImport.update({
  id: '/ease-events/leads/$leadId',
  path: '/ease-events/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsEventsEventIdRoute = EaseEventsEventsEventIdRouteImport.update({
  id: '/ease-events/events/$eventId',
  path: '/ease-events/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EaseEventsClientsClientIdRoute =
  EaseEventsClientsClientIdRouteImport.update({
    id: '/ease-events/clients/$clientId',
    path: '/ease-events/clients/$clientId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConsultationRoute = ApiPublicConsultationRouteImport.update({
  id: '/api/public/consultation',
  path: '/api/public/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEaseEventsPublicInquiryRoute =
  ApiEaseEventsPublicInquiryRouteImport.update({
    id: '/api/ease-events/public-inquiry',
    path: '/api/ease-events/public-inquiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsClientPortalAccessRoute =
  ApiEaseEventsClientPortalAccessRouteImport.update({
    id: '/api/ease-events/client-portal-access',
    path: '/api/ease-events/client-portal-access',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsCheckoutRoute = ApiEaseEventsCheckoutRouteImport.update({
  id: '/api/ease-events/checkout',
  path: '/api/ease-events/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const EaseEventsEventsEventIdEventDayRoute =
  EaseEventsEventsEventIdEventDayRouteImport.update({
    id: '/event-day',
    path: '/event-day',
    getParentRoute: () => EaseEventsEventsEventIdRoute,
  } as any)
const ApiEaseEventsPublicInquiryUploadRoute =
  ApiEaseEventsPublicInquiryUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiEaseEventsPublicInquiryRoute,
  } as any)
const ApiEaseEventsPublicInquiryFinalizeRoute =
  ApiEaseEventsPublicInquiryFinalizeRouteImport.update({
    id: '/finalize',
    path: '/finalize',
    getParentRoute: () => ApiEaseEventsPublicInquiryRoute,
  } as any)
const ApiEaseEventsProposalsSendRoute =
  ApiEaseEventsProposalsSendRouteImport.update({
    id: '/api/ease-events/proposals/send',
    path: '/api/ease-events/proposals/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsProposalsPaymentRoute =
  ApiEaseEventsProposalsPaymentRouteImport.update({
    id: '/api/ease-events/proposals/payment',
    path: '/api/ease-events/proposals/payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsProposalsDraftRoute =
  ApiEaseEventsProposalsDraftRouteImport.update({
    id: '/api/ease-events/proposals/draft',
    path: '/api/ease-events/proposals/draft',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsProposalsBookingStatusRoute =
  ApiEaseEventsProposalsBookingStatusRouteImport.update({
    id: '/api/ease-events/proposals/booking-status',
    path: '/api/ease-events/proposals/booking-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsProposalsBookingApprovalRoute =
  ApiEaseEventsProposalsBookingApprovalRouteImport.update({
    id: '/api/ease-events/proposals/booking-approval',
    path: '/api/ease-events/proposals/booking-approval',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsMeetingsRoute =
  ApiEaseEventsIntegrationsMeetingsRouteImport.update({
    id: '/api/ease-events/integrations/meetings',
    path: '/api/ease-events/integrations/meetings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsAiMeetingSummaryRoute =
  ApiEaseEventsAiMeetingSummaryRouteImport.update({
    id: '/api/ease-events/ai/meeting-summary',
    path: '/api/ease-events/ai/meeting-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsProposalsReviewTokenRoute =
  ApiEaseEventsProposalsReviewTokenRouteImport.update({
    id: '/api/ease-events/proposals/review/$token',
    path: '/api/ease-events/proposals/review/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsOauthStartRoute =
  ApiEaseEventsIntegrationsOauthStartRouteImport.update({
    id: '/api/ease-events/integrations/oauth/start',
    path: '/api/ease-events/integrations/oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsOauthCallbackRoute =
  ApiEaseEventsIntegrationsOauthCallbackRouteImport.update({
    id: '/api/ease-events/integrations/oauth/callback',
    path: '/api/ease-events/integrations/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsMailSyncRoute =
  ApiEaseEventsIntegrationsMailSyncRouteImport.update({
    id: '/api/ease-events/integrations/mail/sync',
    path: '/api/ease-events/integrations/mail/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsMailSendRoute =
  ApiEaseEventsIntegrationsMailSendRouteImport.update({
    id: '/api/ease-events/integrations/mail/send',
    path: '/api/ease-events/integrations/mail/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsFathomSyncRoute =
  ApiEaseEventsIntegrationsFathomSyncRouteImport.update({
    id: '/api/ease-events/integrations/fathom/sync',
    path: '/api/ease-events/integrations/fathom/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsFathomMeetingsRoute =
  ApiEaseEventsIntegrationsFathomMeetingsRouteImport.update({
    id: '/api/ease-events/integrations/fathom/meetings',
    path: '/api/ease-events/integrations/fathom/meetings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsFathomImportRoute =
  ApiEaseEventsIntegrationsFathomImportRouteImport.update({
    id: '/api/ease-events/integrations/fathom/import',
    path: '/api/ease-events/integrations/fathom/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsCalendarSyncRoute =
  ApiEaseEventsIntegrationsCalendarSyncRouteImport.update({
    id: '/api/ease-events/integrations/calendar/sync',
    path: '/api/ease-events/integrations/calendar/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEaseEventsIntegrationsAccountsDisconnectRoute =
  ApiEaseEventsIntegrationsAccountsDisconnectRouteImport.update({
    id: '/api/ease-events/integrations/accounts/disconnect',
    path: '/api/ease-events/integrations/accounts/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/logo-options': typeof LogoOptionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ease-events/budgets': typeof EaseEventsBudgetsRoute
  '/ease-events/calendar': typeof EaseEventsCalendarRoute
  '/ease-events/client-portal': typeof EaseEventsClientPortalRoute
  '/ease-events/communications': typeof EaseEventsCommunicationsRoute
  '/ease-events/files': typeof EaseEventsFilesRoute
  '/ease-events/inquiry': typeof EaseEventsInquiryRoute
  '/ease-events/login': typeof EaseEventsLoginRoute
  '/ease-events/reports': typeof EaseEventsReportsRoute
  '/ease-events/retention': typeof EaseEventsRetentionRoute
  '/ease-events/settings': typeof EaseEventsSettingsRoute
  '/ease-events/tasks': typeof EaseEventsTasksRoute
  '/ease-events/work': typeof EaseEventsWorkRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ease-events/': typeof EaseEventsIndexRoute
  '/api/ease-events/checkout': typeof ApiEaseEventsCheckoutRoute
  '/api/ease-events/client-portal-access': typeof ApiEaseEventsClientPortalAccessRoute
  '/api/ease-events/public-inquiry': typeof ApiEaseEventsPublicInquiryRouteWithChildren
  '/api/public/consultation': typeof ApiPublicConsultationRoute
  '/ease-events/clients/$clientId': typeof EaseEventsClientsClientIdRoute
  '/ease-events/events/$eventId': typeof EaseEventsEventsEventIdRouteWithChildren
  '/ease-events/leads/$leadId': typeof EaseEventsLeadsLeadIdRoute
  '/ease-events/proposals/$token': typeof EaseEventsProposalsTokenRoute
  '/ease-events/vendors/$vendorId': typeof EaseEventsVendorsVendorIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/ease-events/clients/': typeof EaseEventsClientsIndexRoute
  '/ease-events/events/': typeof EaseEventsEventsIndexRoute
  '/ease-events/leads/': typeof EaseEventsLeadsIndexRoute
  '/ease-events/vendors/': typeof EaseEventsVendorsIndexRoute
  '/api/ease-events/ai/meeting-summary': typeof ApiEaseEventsAiMeetingSummaryRoute
  '/api/ease-events/integrations/meetings': typeof ApiEaseEventsIntegrationsMeetingsRoute
  '/api/ease-events/proposals/booking-approval': typeof ApiEaseEventsProposalsBookingApprovalRoute
  '/api/ease-events/proposals/booking-status': typeof ApiEaseEventsProposalsBookingStatusRoute
  '/api/ease-events/proposals/draft': typeof ApiEaseEventsProposalsDraftRoute
  '/api/ease-events/proposals/payment': typeof ApiEaseEventsProposalsPaymentRoute
  '/api/ease-events/proposals/send': typeof ApiEaseEventsProposalsSendRoute
  '/api/ease-events/public-inquiry/finalize': typeof ApiEaseEventsPublicInquiryFinalizeRoute
  '/api/ease-events/public-inquiry/upload': typeof ApiEaseEventsPublicInquiryUploadRoute
  '/ease-events/events/$eventId/event-day': typeof EaseEventsEventsEventIdEventDayRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/ease-events/integrations/accounts/disconnect': typeof ApiEaseEventsIntegrationsAccountsDisconnectRoute
  '/api/ease-events/integrations/calendar/sync': typeof ApiEaseEventsIntegrationsCalendarSyncRoute
  '/api/ease-events/integrations/fathom/import': typeof ApiEaseEventsIntegrationsFathomImportRoute
  '/api/ease-events/integrations/fathom/meetings': typeof ApiEaseEventsIntegrationsFathomMeetingsRoute
  '/api/ease-events/integrations/fathom/sync': typeof ApiEaseEventsIntegrationsFathomSyncRoute
  '/api/ease-events/integrations/mail/send': typeof ApiEaseEventsIntegrationsMailSendRoute
  '/api/ease-events/integrations/mail/sync': typeof ApiEaseEventsIntegrationsMailSyncRoute
  '/api/ease-events/integrations/oauth/callback': typeof ApiEaseEventsIntegrationsOauthCallbackRoute
  '/api/ease-events/integrations/oauth/start': typeof ApiEaseEventsIntegrationsOauthStartRoute
  '/api/ease-events/proposals/review/$token': typeof ApiEaseEventsProposalsReviewTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/logo-options': typeof LogoOptionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ease-events/budgets': typeof EaseEventsBudgetsRoute
  '/ease-events/calendar': typeof EaseEventsCalendarRoute
  '/ease-events/client-portal': typeof EaseEventsClientPortalRoute
  '/ease-events/communications': typeof EaseEventsCommunicationsRoute
  '/ease-events/files': typeof EaseEventsFilesRoute
  '/ease-events/inquiry': typeof EaseEventsInquiryRoute
  '/ease-events/login': typeof EaseEventsLoginRoute
  '/ease-events/reports': typeof EaseEventsReportsRoute
  '/ease-events/retention': typeof EaseEventsRetentionRoute
  '/ease-events/settings': typeof EaseEventsSettingsRoute
  '/ease-events/tasks': typeof EaseEventsTasksRoute
  '/ease-events/work': typeof EaseEventsWorkRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ease-events': typeof EaseEventsIndexRoute
  '/api/ease-events/checkout': typeof ApiEaseEventsCheckoutRoute
  '/api/ease-events/client-portal-access': typeof ApiEaseEventsClientPortalAccessRoute
  '/api/ease-events/public-inquiry': typeof ApiEaseEventsPublicInquiryRouteWithChildren
  '/api/public/consultation': typeof ApiPublicConsultationRoute
  '/ease-events/clients/$clientId': typeof EaseEventsClientsClientIdRoute
  '/ease-events/events/$eventId': typeof EaseEventsEventsEventIdRouteWithChildren
  '/ease-events/leads/$leadId': typeof EaseEventsLeadsLeadIdRoute
  '/ease-events/proposals/$token': typeof EaseEventsProposalsTokenRoute
  '/ease-events/vendors/$vendorId': typeof EaseEventsVendorsVendorIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/ease-events/clients': typeof EaseEventsClientsIndexRoute
  '/ease-events/events': typeof EaseEventsEventsIndexRoute
  '/ease-events/leads': typeof EaseEventsLeadsIndexRoute
  '/ease-events/vendors': typeof EaseEventsVendorsIndexRoute
  '/api/ease-events/ai/meeting-summary': typeof ApiEaseEventsAiMeetingSummaryRoute
  '/api/ease-events/integrations/meetings': typeof ApiEaseEventsIntegrationsMeetingsRoute
  '/api/ease-events/proposals/booking-approval': typeof ApiEaseEventsProposalsBookingApprovalRoute
  '/api/ease-events/proposals/booking-status': typeof ApiEaseEventsProposalsBookingStatusRoute
  '/api/ease-events/proposals/draft': typeof ApiEaseEventsProposalsDraftRoute
  '/api/ease-events/proposals/payment': typeof ApiEaseEventsProposalsPaymentRoute
  '/api/ease-events/proposals/send': typeof ApiEaseEventsProposalsSendRoute
  '/api/ease-events/public-inquiry/finalize': typeof ApiEaseEventsPublicInquiryFinalizeRoute
  '/api/ease-events/public-inquiry/upload': typeof ApiEaseEventsPublicInquiryUploadRoute
  '/ease-events/events/$eventId/event-day': typeof EaseEventsEventsEventIdEventDayRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/ease-events/integrations/accounts/disconnect': typeof ApiEaseEventsIntegrationsAccountsDisconnectRoute
  '/api/ease-events/integrations/calendar/sync': typeof ApiEaseEventsIntegrationsCalendarSyncRoute
  '/api/ease-events/integrations/fathom/import': typeof ApiEaseEventsIntegrationsFathomImportRoute
  '/api/ease-events/integrations/fathom/meetings': typeof ApiEaseEventsIntegrationsFathomMeetingsRoute
  '/api/ease-events/integrations/fathom/sync': typeof ApiEaseEventsIntegrationsFathomSyncRoute
  '/api/ease-events/integrations/mail/send': typeof ApiEaseEventsIntegrationsMailSendRoute
  '/api/ease-events/integrations/mail/sync': typeof ApiEaseEventsIntegrationsMailSyncRoute
  '/api/ease-events/integrations/oauth/callback': typeof ApiEaseEventsIntegrationsOauthCallbackRoute
  '/api/ease-events/integrations/oauth/start': typeof ApiEaseEventsIntegrationsOauthStartRoute
  '/api/ease-events/proposals/review/$token': typeof ApiEaseEventsProposalsReviewTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/logo-options': typeof LogoOptionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ease-events/budgets': typeof EaseEventsBudgetsRoute
  '/ease-events/calendar': typeof EaseEventsCalendarRoute
  '/ease-events/client-portal': typeof EaseEventsClientPortalRoute
  '/ease-events/communications': typeof EaseEventsCommunicationsRoute
  '/ease-events/files': typeof EaseEventsFilesRoute
  '/ease-events/inquiry': typeof EaseEventsInquiryRoute
  '/ease-events/login': typeof EaseEventsLoginRoute
  '/ease-events/reports': typeof EaseEventsReportsRoute
  '/ease-events/retention': typeof EaseEventsRetentionRoute
  '/ease-events/settings': typeof EaseEventsSettingsRoute
  '/ease-events/tasks': typeof EaseEventsTasksRoute
  '/ease-events/work': typeof EaseEventsWorkRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ease-events/': typeof EaseEventsIndexRoute
  '/api/ease-events/checkout': typeof ApiEaseEventsCheckoutRoute
  '/api/ease-events/client-portal-access': typeof ApiEaseEventsClientPortalAccessRoute
  '/api/ease-events/public-inquiry': typeof ApiEaseEventsPublicInquiryRouteWithChildren
  '/api/public/consultation': typeof ApiPublicConsultationRoute
  '/ease-events/clients/$clientId': typeof EaseEventsClientsClientIdRoute
  '/ease-events/events/$eventId': typeof EaseEventsEventsEventIdRouteWithChildren
  '/ease-events/leads/$leadId': typeof EaseEventsLeadsLeadIdRoute
  '/ease-events/proposals/$token': typeof EaseEventsProposalsTokenRoute
  '/ease-events/vendors/$vendorId': typeof EaseEventsVendorsVendorIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/ease-events/clients/': typeof EaseEventsClientsIndexRoute
  '/ease-events/events/': typeof EaseEventsEventsIndexRoute
  '/ease-events/leads/': typeof EaseEventsLeadsIndexRoute
  '/ease-events/vendors/': typeof EaseEventsVendorsIndexRoute
  '/api/ease-events/ai/meeting-summary': typeof ApiEaseEventsAiMeetingSummaryRoute
  '/api/ease-events/integrations/meetings': typeof ApiEaseEventsIntegrationsMeetingsRoute
  '/api/ease-events/proposals/booking-approval': typeof ApiEaseEventsProposalsBookingApprovalRoute
  '/api/ease-events/proposals/booking-status': typeof ApiEaseEventsProposalsBookingStatusRoute
  '/api/ease-events/proposals/draft': typeof ApiEaseEventsProposalsDraftRoute
  '/api/ease-events/proposals/payment': typeof ApiEaseEventsProposalsPaymentRoute
  '/api/ease-events/proposals/send': typeof ApiEaseEventsProposalsSendRoute
  '/api/ease-events/public-inquiry/finalize': typeof ApiEaseEventsPublicInquiryFinalizeRoute
  '/api/ease-events/public-inquiry/upload': typeof ApiEaseEventsPublicInquiryUploadRoute
  '/ease-events/events/$eventId/event-day': typeof EaseEventsEventsEventIdEventDayRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/ease-events/integrations/accounts/disconnect': typeof ApiEaseEventsIntegrationsAccountsDisconnectRoute
  '/api/ease-events/integrations/calendar/sync': typeof ApiEaseEventsIntegrationsCalendarSyncRoute
  '/api/ease-events/integrations/fathom/import': typeof ApiEaseEventsIntegrationsFathomImportRoute
  '/api/ease-events/integrations/fathom/meetings': typeof ApiEaseEventsIntegrationsFathomMeetingsRoute
  '/api/ease-events/integrations/fathom/sync': typeof ApiEaseEventsIntegrationsFathomSyncRoute
  '/api/ease-events/integrations/mail/send': typeof ApiEaseEventsIntegrationsMailSendRoute
  '/api/ease-events/integrations/mail/sync': typeof ApiEaseEventsIntegrationsMailSyncRoute
  '/api/ease-events/integrations/oauth/callback': typeof ApiEaseEventsIntegrationsOauthCallbackRoute
  '/api/ease-events/integrations/oauth/start': typeof ApiEaseEventsIntegrationsOauthStartRoute
  '/api/ease-events/proposals/review/$token': typeof ApiEaseEventsProposalsReviewTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultation'
    | '/logo-options'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/ease-events/budgets'
    | '/ease-events/calendar'
    | '/ease-events/client-portal'
    | '/ease-events/communications'
    | '/ease-events/files'
    | '/ease-events/inquiry'
    | '/ease-events/login'
    | '/ease-events/reports'
    | '/ease-events/retention'
    | '/ease-events/settings'
    | '/ease-events/tasks'
    | '/ease-events/work'
    | '/email/unsubscribe'
    | '/ease-events/'
    | '/api/ease-events/checkout'
    | '/api/ease-events/client-portal-access'
    | '/api/ease-events/public-inquiry'
    | '/api/public/consultation'
    | '/ease-events/clients/$clientId'
    | '/ease-events/events/$eventId'
    | '/ease-events/leads/$leadId'
    | '/ease-events/proposals/$token'
    | '/ease-events/vendors/$vendorId'
    | '/lovable/email/suppression'
    | '/ease-events/clients/'
    | '/ease-events/events/'
    | '/ease-events/leads/'
    | '/ease-events/vendors/'
    | '/api/ease-events/ai/meeting-summary'
    | '/api/ease-events/integrations/meetings'
    | '/api/ease-events/proposals/booking-approval'
    | '/api/ease-events/proposals/booking-status'
    | '/api/ease-events/proposals/draft'
    | '/api/ease-events/proposals/payment'
    | '/api/ease-events/proposals/send'
    | '/api/ease-events/public-inquiry/finalize'
    | '/api/ease-events/public-inquiry/upload'
    | '/ease-events/events/$eventId/event-day'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/ease-events/integrations/accounts/disconnect'
    | '/api/ease-events/integrations/calendar/sync'
    | '/api/ease-events/integrations/fathom/import'
    | '/api/ease-events/integrations/fathom/meetings'
    | '/api/ease-events/integrations/fathom/sync'
    | '/api/ease-events/integrations/mail/send'
    | '/api/ease-events/integrations/mail/sync'
    | '/api/ease-events/integrations/oauth/callback'
    | '/api/ease-events/integrations/oauth/start'
    | '/api/ease-events/proposals/review/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultation'
    | '/logo-options'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/ease-events/budgets'
    | '/ease-events/calendar'
    | '/ease-events/client-portal'
    | '/ease-events/communications'
    | '/ease-events/files'
    | '/ease-events/inquiry'
    | '/ease-events/login'
    | '/ease-events/reports'
    | '/ease-events/retention'
    | '/ease-events/settings'
    | '/ease-events/tasks'
    | '/ease-events/work'
    | '/email/unsubscribe'
    | '/ease-events'
    | '/api/ease-events/checkout'
    | '/api/ease-events/client-portal-access'
    | '/api/ease-events/public-inquiry'
    | '/api/public/consultation'
    | '/ease-events/clients/$clientId'
    | '/ease-events/events/$eventId'
    | '/ease-events/leads/$leadId'
    | '/ease-events/proposals/$token'
    | '/ease-events/vendors/$vendorId'
    | '/lovable/email/suppression'
    | '/ease-events/clients'
    | '/ease-events/events'
    | '/ease-events/leads'
    | '/ease-events/vendors'
    | '/api/ease-events/ai/meeting-summary'
    | '/api/ease-events/integrations/meetings'
    | '/api/ease-events/proposals/booking-approval'
    | '/api/ease-events/proposals/booking-status'
    | '/api/ease-events/proposals/draft'
    | '/api/ease-events/proposals/payment'
    | '/api/ease-events/proposals/send'
    | '/api/ease-events/public-inquiry/finalize'
    | '/api/ease-events/public-inquiry/upload'
    | '/ease-events/events/$eventId/event-day'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/ease-events/integrations/accounts/disconnect'
    | '/api/ease-events/integrations/calendar/sync'
    | '/api/ease-events/integrations/fathom/import'
    | '/api/ease-events/integrations/fathom/meetings'
    | '/api/ease-events/integrations/fathom/sync'
    | '/api/ease-events/integrations/mail/send'
    | '/api/ease-events/integrations/mail/sync'
    | '/api/ease-events/integrations/oauth/callback'
    | '/api/ease-events/integrations/oauth/start'
    | '/api/ease-events/proposals/review/$token'
  id:
    | '__root__'
    | '/'
    | '/consultation'
    | '/logo-options'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/ease-events/budgets'
    | '/ease-events/calendar'
    | '/ease-events/client-portal'
    | '/ease-events/communications'
    | '/ease-events/files'
    | '/ease-events/inquiry'
    | '/ease-events/login'
    | '/ease-events/reports'
    | '/ease-events/retention'
    | '/ease-events/settings'
    | '/ease-events/tasks'
    | '/ease-events/work'
    | '/email/unsubscribe'
    | '/ease-events/'
    | '/api/ease-events/checkout'
    | '/api/ease-events/client-portal-access'
    | '/api/ease-events/public-inquiry'
    | '/api/public/consultation'
    | '/ease-events/clients/$clientId'
    | '/ease-events/events/$eventId'
    | '/ease-events/leads/$leadId'
    | '/ease-events/proposals/$token'
    | '/ease-events/vendors/$vendorId'
    | '/lovable/email/suppression'
    | '/ease-events/clients/'
    | '/ease-events/events/'
    | '/ease-events/leads/'
    | '/ease-events/vendors/'
    | '/api/ease-events/ai/meeting-summary'
    | '/api/ease-events/integrations/meetings'
    | '/api/ease-events/proposals/booking-approval'
    | '/api/ease-events/proposals/booking-status'
    | '/api/ease-events/proposals/draft'
    | '/api/ease-events/proposals/payment'
    | '/api/ease-events/proposals/send'
    | '/api/ease-events/public-inquiry/finalize'
    | '/api/ease-events/public-inquiry/upload'
    | '/ease-events/events/$eventId/event-day'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/ease-events/integrations/accounts/disconnect'
    | '/api/ease-events/integrations/calendar/sync'
    | '/api/ease-events/integrations/fathom/import'
    | '/api/ease-events/integrations/fathom/meetings'
    | '/api/ease-events/integrations/fathom/sync'
    | '/api/ease-events/integrations/mail/send'
    | '/api/ease-events/integrations/mail/sync'
    | '/api/ease-events/integrations/oauth/callback'
    | '/api/ease-events/integrations/oauth/start'
    | '/api/ease-events/proposals/review/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultationRoute: typeof ConsultationRoute
  LogoOptionsRoute: typeof LogoOptionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EaseEventsBudgetsRoute: typeof EaseEventsBudgetsRoute
  EaseEventsCalendarRoute: typeof EaseEventsCalendarRoute
  EaseEventsClientPortalRoute: typeof EaseEventsClientPortalRoute
  EaseEventsCommunicationsRoute: typeof EaseEventsCommunicationsRoute
  EaseEventsFilesRoute: typeof EaseEventsFilesRoute
  EaseEventsInquiryRoute: typeof EaseEventsInquiryRoute
  EaseEventsLoginRoute: typeof EaseEventsLoginRoute
  EaseEventsReportsRoute: typeof EaseEventsReportsRoute
  EaseEventsRetentionRoute: typeof EaseEventsRetentionRoute
  EaseEventsSettingsRoute: typeof EaseEventsSettingsRoute
  EaseEventsTasksRoute: typeof EaseEventsTasksRoute
  EaseEventsWorkRoute: typeof EaseEventsWorkRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EaseEventsIndexRoute: typeof EaseEventsIndexRoute
  ApiEaseEventsCheckoutRoute: typeof ApiEaseEventsCheckoutRoute
  ApiEaseEventsClientPortalAccessRoute: typeof ApiEaseEventsClientPortalAccessRoute
  ApiEaseEventsPublicInquiryRoute: typeof ApiEaseEventsPublicInquiryRouteWithChildren
  ApiPublicConsultationRoute: typeof ApiPublicConsultationRoute
  EaseEventsClientsClientIdRoute: typeof EaseEventsClientsClientIdRoute
  EaseEventsEventsEventIdRoute: typeof EaseEventsEventsEventIdRouteWithChildren
  EaseEventsLeadsLeadIdRoute: typeof EaseEventsLeadsLeadIdRoute
  EaseEventsProposalsTokenRoute: typeof EaseEventsProposalsTokenRoute
  EaseEventsVendorsVendorIdRoute: typeof EaseEventsVendorsVendorIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  EaseEventsClientsIndexRoute: typeof EaseEventsClientsIndexRoute
  EaseEventsEventsIndexRoute: typeof EaseEventsEventsIndexRoute
  EaseEventsLeadsIndexRoute: typeof EaseEventsLeadsIndexRoute
  EaseEventsVendorsIndexRoute: typeof EaseEventsVendorsIndexRoute
  ApiEaseEventsAiMeetingSummaryRoute: typeof ApiEaseEventsAiMeetingSummaryRoute
  ApiEaseEventsIntegrationsMeetingsRoute: typeof ApiEaseEventsIntegrationsMeetingsRoute
  ApiEaseEventsProposalsBookingApprovalRoute: typeof ApiEaseEventsProposalsBookingApprovalRoute
  ApiEaseEventsProposalsBookingStatusRoute: typeof ApiEaseEventsProposalsBookingStatusRoute
  ApiEaseEventsProposalsDraftRoute: typeof ApiEaseEventsProposalsDraftRoute
  ApiEaseEventsProposalsPaymentRoute: typeof ApiEaseEventsProposalsPaymentRoute
  ApiEaseEventsProposalsSendRoute: typeof ApiEaseEventsProposalsSendRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiEaseEventsIntegrationsAccountsDisconnectRoute: typeof ApiEaseEventsIntegrationsAccountsDisconnectRoute
  ApiEaseEventsIntegrationsCalendarSyncRoute: typeof ApiEaseEventsIntegrationsCalendarSyncRoute
  ApiEaseEventsIntegrationsFathomImportRoute: typeof ApiEaseEventsIntegrationsFathomImportRoute
  ApiEaseEventsIntegrationsFathomMeetingsRoute: typeof ApiEaseEventsIntegrationsFathomMeetingsRoute
  ApiEaseEventsIntegrationsFathomSyncRoute: typeof ApiEaseEventsIntegrationsFathomSyncRoute
  ApiEaseEventsIntegrationsMailSendRoute: typeof ApiEaseEventsIntegrationsMailSendRoute
  ApiEaseEventsIntegrationsMailSyncRoute: typeof ApiEaseEventsIntegrationsMailSyncRoute
  ApiEaseEventsIntegrationsOauthCallbackRoute: typeof ApiEaseEventsIntegrationsOauthCallbackRoute
  ApiEaseEventsIntegrationsOauthStartRoute: typeof ApiEaseEventsIntegrationsOauthStartRoute
  ApiEaseEventsProposalsReviewTokenRoute: typeof ApiEaseEventsProposalsReviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-options': {
      id: '/logo-options'
      path: '/logo-options'
      fullPath: '/logo-options'
      preLoaderRoute: typeof LogoOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/': {
      id: '/ease-events/'
      path: '/ease-events'
      fullPath: '/ease-events/'
      preLoaderRoute: typeof EaseEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/work': {
      id: '/ease-events/work'
      path: '/ease-events/work'
      fullPath: '/ease-events/work'
      preLoaderRoute: typeof EaseEventsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/tasks': {
      id: '/ease-events/tasks'
      path: '/ease-events/tasks'
      fullPath: '/ease-events/tasks'
      preLoaderRoute: typeof EaseEventsTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/settings': {
      id: '/ease-events/settings'
      path: '/ease-events/settings'
      fullPath: '/ease-events/settings'
      preLoaderRoute: typeof EaseEventsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/retention': {
      id: '/ease-events/retention'
      path: '/ease-events/retention'
      fullPath: '/ease-events/retention'
      preLoaderRoute: typeof EaseEventsRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/reports': {
      id: '/ease-events/reports'
      path: '/ease-events/reports'
      fullPath: '/ease-events/reports'
      preLoaderRoute: typeof EaseEventsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/login': {
      id: '/ease-events/login'
      path: '/ease-events/login'
      fullPath: '/ease-events/login'
      preLoaderRoute: typeof EaseEventsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/inquiry': {
      id: '/ease-events/inquiry'
      path: '/ease-events/inquiry'
      fullPath: '/ease-events/inquiry'
      preLoaderRoute: typeof EaseEventsInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/files': {
      id: '/ease-events/files'
      path: '/ease-events/files'
      fullPath: '/ease-events/files'
      preLoaderRoute: typeof EaseEventsFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/communications': {
      id: '/ease-events/communications'
      path: '/ease-events/communications'
      fullPath: '/ease-events/communications'
      preLoaderRoute: typeof EaseEventsCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/client-portal': {
      id: '/ease-events/client-portal'
      path: '/ease-events/client-portal'
      fullPath: '/ease-events/client-portal'
      preLoaderRoute: typeof EaseEventsClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/calendar': {
      id: '/ease-events/calendar'
      path: '/ease-events/calendar'
      fullPath: '/ease-events/calendar'
      preLoaderRoute: typeof EaseEventsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/budgets': {
      id: '/ease-events/budgets'
      path: '/ease-events/budgets'
      fullPath: '/ease-events/budgets'
      preLoaderRoute: typeof EaseEventsBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/vendors/': {
      id: '/ease-events/vendors/'
      path: '/ease-events/vendors'
      fullPath: '/ease-events/vendors/'
      preLoaderRoute: typeof EaseEventsVendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/leads/': {
      id: '/ease-events/leads/'
      path: '/ease-events/leads'
      fullPath: '/ease-events/leads/'
      preLoaderRoute: typeof EaseEventsLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/events/': {
      id: '/ease-events/events/'
      path: '/ease-events/events'
      fullPath: '/ease-events/events/'
      preLoaderRoute: typeof EaseEventsEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/clients/': {
      id: '/ease-events/clients/'
      path: '/ease-events/clients'
      fullPath: '/ease-events/clients/'
      preLoaderRoute: typeof EaseEventsClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/vendors/$vendorId': {
      id: '/ease-events/vendors/$vendorId'
      path: '/ease-events/vendors/$vendorId'
      fullPath: '/ease-events/vendors/$vendorId'
      preLoaderRoute: typeof EaseEventsVendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/proposals/$token': {
      id: '/ease-events/proposals/$token'
      path: '/ease-events/proposals/$token'
      fullPath: '/ease-events/proposals/$token'
      preLoaderRoute: typeof EaseEventsProposalsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/leads/$leadId': {
      id: '/ease-events/leads/$leadId'
      path: '/ease-events/leads/$leadId'
      fullPath: '/ease-events/leads/$leadId'
      preLoaderRoute: typeof EaseEventsLeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/events/$eventId': {
      id: '/ease-events/events/$eventId'
      path: '/ease-events/events/$eventId'
      fullPath: '/ease-events/events/$eventId'
      preLoaderRoute: typeof EaseEventsEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/clients/$clientId': {
      id: '/ease-events/clients/$clientId'
      path: '/ease-events/clients/$clientId'
      fullPath: '/ease-events/clients/$clientId'
      preLoaderRoute: typeof EaseEventsClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consultation': {
      id: '/api/public/consultation'
      path: '/api/public/consultation'
      fullPath: '/api/public/consultation'
      preLoaderRoute: typeof ApiPublicConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/public-inquiry': {
      id: '/api/ease-events/public-inquiry'
      path: '/api/ease-events/public-inquiry'
      fullPath: '/api/ease-events/public-inquiry'
      preLoaderRoute: typeof ApiEaseEventsPublicInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/client-portal-access': {
      id: '/api/ease-events/client-portal-access'
      path: '/api/ease-events/client-portal-access'
      fullPath: '/api/ease-events/client-portal-access'
      preLoaderRoute: typeof ApiEaseEventsClientPortalAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/checkout': {
      id: '/api/ease-events/checkout'
      path: '/api/ease-events/checkout'
      fullPath: '/api/ease-events/checkout'
      preLoaderRoute: typeof ApiEaseEventsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ease-events/events/$eventId/event-day': {
      id: '/ease-events/events/$eventId/event-day'
      path: '/event-day'
      fullPath: '/ease-events/events/$eventId/event-day'
      preLoaderRoute: typeof EaseEventsEventsEventIdEventDayRouteImport
      parentRoute: typeof EaseEventsEventsEventIdRoute
    }
    '/api/ease-events/public-inquiry/upload': {
      id: '/api/ease-events/public-inquiry/upload'
      path: '/upload'
      fullPath: '/api/ease-events/public-inquiry/upload'
      preLoaderRoute: typeof ApiEaseEventsPublicInquiryUploadRouteImport
      parentRoute: typeof ApiEaseEventsPublicInquiryRoute
    }
    '/api/ease-events/public-inquiry/finalize': {
      id: '/api/ease-events/public-inquiry/finalize'
      path: '/finalize'
      fullPath: '/api/ease-events/public-inquiry/finalize'
      preLoaderRoute: typeof ApiEaseEventsPublicInquiryFinalizeRouteImport
      parentRoute: typeof ApiEaseEventsPublicInquiryRoute
    }
    '/api/ease-events/proposals/send': {
      id: '/api/ease-events/proposals/send'
      path: '/api/ease-events/proposals/send'
      fullPath: '/api/ease-events/proposals/send'
      preLoaderRoute: typeof ApiEaseEventsProposalsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/proposals/payment': {
      id: '/api/ease-events/proposals/payment'
      path: '/api/ease-events/proposals/payment'
      fullPath: '/api/ease-events/proposals/payment'
      preLoaderRoute: typeof ApiEaseEventsProposalsPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/proposals/draft': {
      id: '/api/ease-events/proposals/draft'
      path: '/api/ease-events/proposals/draft'
      fullPath: '/api/ease-events/proposals/draft'
      preLoaderRoute: typeof ApiEaseEventsProposalsDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/proposals/booking-status': {
      id: '/api/ease-events/proposals/booking-status'
      path: '/api/ease-events/proposals/booking-status'
      fullPath: '/api/ease-events/proposals/booking-status'
      preLoaderRoute: typeof ApiEaseEventsProposalsBookingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/proposals/booking-approval': {
      id: '/api/ease-events/proposals/booking-approval'
      path: '/api/ease-events/proposals/booking-approval'
      fullPath: '/api/ease-events/proposals/booking-approval'
      preLoaderRoute: typeof ApiEaseEventsProposalsBookingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/meetings': {
      id: '/api/ease-events/integrations/meetings'
      path: '/api/ease-events/integrations/meetings'
      fullPath: '/api/ease-events/integrations/meetings'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/ai/meeting-summary': {
      id: '/api/ease-events/ai/meeting-summary'
      path: '/api/ease-events/ai/meeting-summary'
      fullPath: '/api/ease-events/ai/meeting-summary'
      preLoaderRoute: typeof ApiEaseEventsAiMeetingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/proposals/review/$token': {
      id: '/api/ease-events/proposals/review/$token'
      path: '/api/ease-events/proposals/review/$token'
      fullPath: '/api/ease-events/proposals/review/$token'
      preLoaderRoute: typeof ApiEaseEventsProposalsReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/oauth/start': {
      id: '/api/ease-events/integrations/oauth/start'
      path: '/api/ease-events/integrations/oauth/start'
      fullPath: '/api/ease-events/integrations/oauth/start'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/oauth/callback': {
      id: '/api/ease-events/integrations/oauth/callback'
      path: '/api/ease-events/integrations/oauth/callback'
      fullPath: '/api/ease-events/integrations/oauth/callback'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/mail/sync': {
      id: '/api/ease-events/integrations/mail/sync'
      path: '/api/ease-events/integrations/mail/sync'
      fullPath: '/api/ease-events/integrations/mail/sync'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsMailSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/mail/send': {
      id: '/api/ease-events/integrations/mail/send'
      path: '/api/ease-events/integrations/mail/send'
      fullPath: '/api/ease-events/integrations/mail/send'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsMailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/fathom/sync': {
      id: '/api/ease-events/integrations/fathom/sync'
      path: '/api/ease-events/integrations/fathom/sync'
      fullPath: '/api/ease-events/integrations/fathom/sync'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsFathomSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/fathom/meetings': {
      id: '/api/ease-events/integrations/fathom/meetings'
      path: '/api/ease-events/integrations/fathom/meetings'
      fullPath: '/api/ease-events/integrations/fathom/meetings'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsFathomMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/fathom/import': {
      id: '/api/ease-events/integrations/fathom/import'
      path: '/api/ease-events/integrations/fathom/import'
      fullPath: '/api/ease-events/integrations/fathom/import'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsFathomImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/calendar/sync': {
      id: '/api/ease-events/integrations/calendar/sync'
      path: '/api/ease-events/integrations/calendar/sync'
      fullPath: '/api/ease-events/integrations/calendar/sync'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ease-events/integrations/accounts/disconnect': {
      id: '/api/ease-events/integrations/accounts/disconnect'
      path: '/api/ease-events/integrations/accounts/disconnect'
      fullPath: '/api/ease-events/integrations/accounts/disconnect'
      preLoaderRoute: typeof ApiEaseEventsIntegrationsAccountsDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiEaseEventsPublicInquiryRouteChildren {
  ApiEaseEventsPublicInquiryFinalizeRoute: typeof ApiEaseEventsPublicInquiryFinalizeRoute
  ApiEaseEventsPublicInquiryUploadRoute: typeof ApiEaseEventsPublicInquiryUploadRoute
}

const ApiEaseEventsPublicInquiryRouteChildren: ApiEaseEventsPublicInquiryRouteChildren =
  {
    ApiEaseEventsPublicInquiryFinalizeRoute:
      ApiEaseEventsPublicInquiryFinalizeRoute,
    ApiEaseEventsPublicInquiryUploadRoute:
      ApiEaseEventsPublicInquiryUploadRoute,
  }

const ApiEaseEventsPublicInquiryRouteWithChildren =
  ApiEaseEventsPublicInquiryRoute._addFileChildren(
    ApiEaseEventsPublicInquiryRouteChildren,
  )

interface EaseEventsEventsEventIdRouteChildren {
  EaseEventsEventsEventIdEventDayRoute: typeof EaseEventsEventsEventIdEventDayRoute
}

const EaseEventsEventsEventIdRouteChildren: EaseEventsEventsEventIdRouteChildren =
  {
    EaseEventsEventsEventIdEventDayRoute: EaseEventsEventsEventIdEventDayRoute,
  }

const EaseEventsEventsEventIdRouteWithChildren =
  EaseEventsEventsEventIdRoute._addFileChildren(
    EaseEventsEventsEventIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultationRoute: ConsultationRoute,
  LogoOptionsRoute: LogoOptionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EaseEventsBudgetsRoute: EaseEventsBudgetsRoute,
  EaseEventsCalendarRoute: EaseEventsCalendarRoute,
  EaseEventsClientPortalRoute: EaseEventsClientPortalRoute,
  EaseEventsCommunicationsRoute: EaseEventsCommunicationsRoute,
  EaseEventsFilesRoute: EaseEventsFilesRoute,
  EaseEventsInquiryRoute: EaseEventsInquiryRoute,
  EaseEventsLoginRoute: EaseEventsLoginRoute,
  EaseEventsReportsRoute: EaseEventsReportsRoute,
  EaseEventsRetentionRoute: EaseEventsRetentionRoute,
  EaseEventsSettingsRoute: EaseEventsSettingsRoute,
  EaseEventsTasksRoute: EaseEventsTasksRoute,
  EaseEventsWorkRoute: EaseEventsWorkRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EaseEventsIndexRoute: EaseEventsIndexRoute,
  ApiEaseEventsCheckoutRoute: ApiEaseEventsCheckoutRoute,
  ApiEaseEventsClientPortalAccessRoute: ApiEaseEventsClientPortalAccessRoute,
  ApiEaseEventsPublicInquiryRoute: ApiEaseEventsPublicInquiryRouteWithChildren,
  ApiPublicConsultationRoute: ApiPublicConsultationRoute,
  EaseEventsClientsClientIdRoute: EaseEventsClientsClientIdRoute,
  EaseEventsEventsEventIdRoute: EaseEventsEventsEventIdRouteWithChildren,
  EaseEventsLeadsLeadIdRoute: EaseEventsLeadsLeadIdRoute,
  EaseEventsProposalsTokenRoute: EaseEventsProposalsTokenRoute,
  EaseEventsVendorsVendorIdRoute: EaseEventsVendorsVendorIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  EaseEventsClientsIndexRoute: EaseEventsClientsIndexRoute,
  EaseEventsEventsIndexRoute: EaseEventsEventsIndexRoute,
  EaseEventsLeadsIndexRoute: EaseEventsLeadsIndexRoute,
  EaseEventsVendorsIndexRoute: EaseEventsVendorsIndexRoute,
  ApiEaseEventsAiMeetingSummaryRoute: ApiEaseEventsAiMeetingSummaryRoute,
  ApiEaseEventsIntegrationsMeetingsRoute:
    ApiEaseEventsIntegrationsMeetingsRoute,
  ApiEaseEventsProposalsBookingApprovalRoute:
    ApiEaseEventsProposalsBookingApprovalRoute,
  ApiEaseEventsProposalsBookingStatusRoute:
    ApiEaseEventsProposalsBookingStatusRoute,
  ApiEaseEventsProposalsDraftRoute: ApiEaseEventsProposalsDraftRoute,
  ApiEaseEventsProposalsPaymentRoute: ApiEaseEventsProposalsPaymentRoute,
  ApiEaseEventsProposalsSendRoute: ApiEaseEventsProposalsSendRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiEaseEventsIntegrationsAccountsDisconnectRoute:
    ApiEaseEventsIntegrationsAccountsDisconnectRoute,
  ApiEaseEventsIntegrationsCalendarSyncRoute:
    ApiEaseEventsIntegrationsCalendarSyncRoute,
  ApiEaseEventsIntegrationsFathomImportRoute:
    ApiEaseEventsIntegrationsFathomImportRoute,
  ApiEaseEventsIntegrationsFathomMeetingsRoute:
    ApiEaseEventsIntegrationsFathomMeetingsRoute,
  ApiEaseEventsIntegrationsFathomSyncRoute:
    ApiEaseEventsIntegrationsFathomSyncRoute,
  ApiEaseEventsIntegrationsMailSendRoute:
    ApiEaseEventsIntegrationsMailSendRoute,
  ApiEaseEventsIntegrationsMailSyncRoute:
    ApiEaseEventsIntegrationsMailSyncRoute,
  ApiEaseEventsIntegrationsOauthCallbackRoute:
    ApiEaseEventsIntegrationsOauthCallbackRoute,
  ApiEaseEventsIntegrationsOauthStartRoute:
    ApiEaseEventsIntegrationsOauthStartRoute,
  ApiEaseEventsProposalsReviewTokenRoute:
    ApiEaseEventsProposalsReviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
